// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tse.Inputs
{

    public sealed class CngwCanaryRuleCanaryRuleBalancedServiceListGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("percent")]
        public Input<double>? Percent { get; set; }

        [Input("serviceId")]
        public Input<string>? ServiceId { get; set; }

        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        [Input("upstreamName")]
        public Input<string>? UpstreamName { get; set; }

        public CngwCanaryRuleCanaryRuleBalancedServiceListGetArgs()
        {
        }
        public static new CngwCanaryRuleCanaryRuleBalancedServiceListGetArgs Empty => new CngwCanaryRuleCanaryRuleBalancedServiceListGetArgs();
    }
}
