// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Lighthouse.Inputs
{

    public sealed class FirewallRuleFirewallRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("action")]
        public Input<string>? Action { get; set; }

        [Input("cidrBlock")]
        public Input<string>? CidrBlock { get; set; }

        [Input("firewallRuleDescription")]
        public Input<string>? FirewallRuleDescription { get; set; }

        [Input("port")]
        public Input<string>? Port { get; set; }

        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        public FirewallRuleFirewallRuleArgs()
        {
        }
        public static new FirewallRuleFirewallRuleArgs Empty => new FirewallRuleFirewallRuleArgs();
    }
}
