// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class TranscodeTemplateEnhanceConfigVideoEnhanceScratchRepair
    {
        public readonly double? Intensity;
        public readonly string? Switch;

        [OutputConstructor]
        private TranscodeTemplateEnhanceConfigVideoEnhanceScratchRepair(
            double? intensity,

            string? @switch)
        {
            Intensity = intensity;
            Switch = @switch;
        }
    }
}
