// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class WorkflowMediaProcessTaskAdaptiveDynamicStreamingTaskSet
    {
        public readonly int Definition;
        public readonly string? OutputObjectPath;
        public readonly Outputs.WorkflowMediaProcessTaskAdaptiveDynamicStreamingTaskSetOutputStorage? OutputStorage;
        public readonly string? SegmentObjectName;
        public readonly string? SubStreamObjectName;
        public readonly ImmutableArray<Outputs.WorkflowMediaProcessTaskAdaptiveDynamicStreamingTaskSetWatermarkSet> WatermarkSets;

        [OutputConstructor]
        private WorkflowMediaProcessTaskAdaptiveDynamicStreamingTaskSet(
            int definition,

            string? outputObjectPath,

            Outputs.WorkflowMediaProcessTaskAdaptiveDynamicStreamingTaskSetOutputStorage? outputStorage,

            string? segmentObjectName,

            string? subStreamObjectName,

            ImmutableArray<Outputs.WorkflowMediaProcessTaskAdaptiveDynamicStreamingTaskSetWatermarkSet> watermarkSets)
        {
            Definition = definition;
            OutputObjectPath = outputObjectPath;
            OutputStorage = outputStorage;
            SegmentObjectName = segmentObjectName;
            SubStreamObjectName = subStreamObjectName;
            WatermarkSets = watermarkSets;
        }
    }
}
