// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Inputs
{

    public sealed class TranscodeTemplateEnhanceConfigVideoEnhanceArtifactRepairGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("switch")]
        public Input<string>? Switch { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public TranscodeTemplateEnhanceConfigVideoEnhanceArtifactRepairGetArgs()
        {
        }
        public static new TranscodeTemplateEnhanceConfigVideoEnhanceArtifactRepairGetArgs Empty => new TranscodeTemplateEnhanceConfigVideoEnhanceArtifactRepairGetArgs();
    }
}
