// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dcdb.Outputs
{

    [OutputType]
    public sealed class GetParametersListConstraintResult
    {
        public readonly string Enum;
        public readonly ImmutableArray<Outputs.GetParametersListConstraintRangeResult> Ranges;
        public readonly string String;
        public readonly string Type;

        [OutputConstructor]
        private GetParametersListConstraintResult(
            string @enum,

            ImmutableArray<Outputs.GetParametersListConstraintRangeResult> ranges,

            string @string,

            string type)
        {
            Enum = @enum;
            Ranges = ranges;
            String = @string;
            Type = type;
        }
    }
}
