// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mdl.Inputs
{

    public sealed class StreamLiveInputInputSettingGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        [Input("delayTime")]
        public Input<int>? DelayTime { get; set; }

        [Input("inputAddress")]
        public Input<string>? InputAddress { get; set; }

        [Input("inputDomain")]
        public Input<string>? InputDomain { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("sourceType")]
        public Input<string>? SourceType { get; set; }

        [Input("sourceUrl")]
        public Input<string>? SourceUrl { get; set; }

        [Input("streamName")]
        public Input<string>? StreamName { get; set; }

        [Input("userName")]
        public Input<string>? UserName { get; set; }

        public StreamLiveInputInputSettingGetArgs()
        {
        }
        public static new StreamLiveInputInputSettingGetArgs Empty => new StreamLiveInputInputSettingGetArgs();
    }
}
