// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package as

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetScalingGroups(ctx *pulumi.Context, args *GetScalingGroupsArgs, opts ...pulumi.InvokeOption) (*GetScalingGroupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetScalingGroupsResult
	err := ctx.Invoke("tencentcloud:As/getScalingGroups:getScalingGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getScalingGroups.
type GetScalingGroupsArgs struct {
	ConfigurationId  *string                `pulumi:"configurationId"`
	ResultOutputFile *string                `pulumi:"resultOutputFile"`
	ScalingGroupId   *string                `pulumi:"scalingGroupId"`
	ScalingGroupName *string                `pulumi:"scalingGroupName"`
	Tags             map[string]interface{} `pulumi:"tags"`
}

// A collection of values returned by getScalingGroups.
type GetScalingGroupsResult struct {
	ConfigurationId *string `pulumi:"configurationId"`
	// The provider-assigned unique ID for this managed resource.
	Id                string                             `pulumi:"id"`
	ResultOutputFile  *string                            `pulumi:"resultOutputFile"`
	ScalingGroupId    *string                            `pulumi:"scalingGroupId"`
	ScalingGroupLists []GetScalingGroupsScalingGroupList `pulumi:"scalingGroupLists"`
	ScalingGroupName  *string                            `pulumi:"scalingGroupName"`
	Tags              map[string]interface{}             `pulumi:"tags"`
}

func GetScalingGroupsOutput(ctx *pulumi.Context, args GetScalingGroupsOutputArgs, opts ...pulumi.InvokeOption) GetScalingGroupsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetScalingGroupsResult, error) {
			args := v.(GetScalingGroupsArgs)
			r, err := GetScalingGroups(ctx, &args, opts...)
			var s GetScalingGroupsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetScalingGroupsResultOutput)
}

// A collection of arguments for invoking getScalingGroups.
type GetScalingGroupsOutputArgs struct {
	ConfigurationId  pulumi.StringPtrInput `pulumi:"configurationId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
	ScalingGroupId   pulumi.StringPtrInput `pulumi:"scalingGroupId"`
	ScalingGroupName pulumi.StringPtrInput `pulumi:"scalingGroupName"`
	Tags             pulumi.MapInput       `pulumi:"tags"`
}

func (GetScalingGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetScalingGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getScalingGroups.
type GetScalingGroupsResultOutput struct{ *pulumi.OutputState }

func (GetScalingGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetScalingGroupsResult)(nil)).Elem()
}

func (o GetScalingGroupsResultOutput) ToGetScalingGroupsResultOutput() GetScalingGroupsResultOutput {
	return o
}

func (o GetScalingGroupsResultOutput) ToGetScalingGroupsResultOutputWithContext(ctx context.Context) GetScalingGroupsResultOutput {
	return o
}

func (o GetScalingGroupsResultOutput) ConfigurationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) *string { return v.ConfigurationId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetScalingGroupsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetScalingGroupsResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetScalingGroupsResultOutput) ScalingGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) *string { return v.ScalingGroupId }).(pulumi.StringPtrOutput)
}

func (o GetScalingGroupsResultOutput) ScalingGroupLists() GetScalingGroupsScalingGroupListArrayOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) []GetScalingGroupsScalingGroupList { return v.ScalingGroupLists }).(GetScalingGroupsScalingGroupListArrayOutput)
}

func (o GetScalingGroupsResultOutput) ScalingGroupName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) *string { return v.ScalingGroupName }).(pulumi.StringPtrOutput)
}

func (o GetScalingGroupsResultOutput) Tags() pulumi.MapOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) map[string]interface{} { return v.Tags }).(pulumi.MapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetScalingGroupsResultOutput{})
}
