// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getRollbackRangeTime(args: GetRollbackRangeTimeArgs, opts?: pulumi.InvokeOptions): Promise<GetRollbackRangeTimeResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Mysql/getRollbackRangeTime:getRollbackRangeTime", {
        "backupRegion": args.backupRegion,
        "instanceIds": args.instanceIds,
        "isRemoteZone": args.isRemoteZone,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getRollbackRangeTime.
 */
export interface GetRollbackRangeTimeArgs {
    backupRegion?: string;
    instanceIds: string[];
    isRemoteZone?: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getRollbackRangeTime.
 */
export interface GetRollbackRangeTimeResult {
    readonly backupRegion?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceIds: string[];
    readonly isRemoteZone?: string;
    readonly items: outputs.Mysql.GetRollbackRangeTimeItem[];
    readonly resultOutputFile?: string;
}
export function getRollbackRangeTimeOutput(args: GetRollbackRangeTimeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRollbackRangeTimeResult> {
    return pulumi.output(args).apply((a: any) => getRollbackRangeTime(a, opts))
}

/**
 * A collection of arguments for invoking getRollbackRangeTime.
 */
export interface GetRollbackRangeTimeOutputArgs {
    backupRegion?: pulumi.Input<string>;
    instanceIds: pulumi.Input<pulumi.Input<string>[]>;
    isRemoteZone?: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
