// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clb

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInstanceDetail(ctx *pulumi.Context, args *GetInstanceDetailArgs, opts ...pulumi.InvokeOption) (*GetInstanceDetailResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInstanceDetailResult
	err := ctx.Invoke("tencentcloud:Clb/getInstanceDetail:getInstanceDetail", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstanceDetail.
type GetInstanceDetailArgs struct {
	Fields           []string                  `pulumi:"fields"`
	Filters          []GetInstanceDetailFilter `pulumi:"filters"`
	ResultOutputFile *string                   `pulumi:"resultOutputFile"`
	TargetType       *string                   `pulumi:"targetType"`
}

// A collection of values returned by getInstanceDetail.
type GetInstanceDetailResult struct {
	Fields  []string                  `pulumi:"fields"`
	Filters []GetInstanceDetailFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id                     string                                   `pulumi:"id"`
	LoadBalancerDetailSets []GetInstanceDetailLoadBalancerDetailSet `pulumi:"loadBalancerDetailSets"`
	ResultOutputFile       *string                                  `pulumi:"resultOutputFile"`
	TargetType             *string                                  `pulumi:"targetType"`
}

func GetInstanceDetailOutput(ctx *pulumi.Context, args GetInstanceDetailOutputArgs, opts ...pulumi.InvokeOption) GetInstanceDetailResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetInstanceDetailResult, error) {
			args := v.(GetInstanceDetailArgs)
			r, err := GetInstanceDetail(ctx, &args, opts...)
			var s GetInstanceDetailResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetInstanceDetailResultOutput)
}

// A collection of arguments for invoking getInstanceDetail.
type GetInstanceDetailOutputArgs struct {
	Fields           pulumi.StringArrayInput           `pulumi:"fields"`
	Filters          GetInstanceDetailFilterArrayInput `pulumi:"filters"`
	ResultOutputFile pulumi.StringPtrInput             `pulumi:"resultOutputFile"`
	TargetType       pulumi.StringPtrInput             `pulumi:"targetType"`
}

func (GetInstanceDetailOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceDetailArgs)(nil)).Elem()
}

// A collection of values returned by getInstanceDetail.
type GetInstanceDetailResultOutput struct{ *pulumi.OutputState }

func (GetInstanceDetailResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceDetailResult)(nil)).Elem()
}

func (o GetInstanceDetailResultOutput) ToGetInstanceDetailResultOutput() GetInstanceDetailResultOutput {
	return o
}

func (o GetInstanceDetailResultOutput) ToGetInstanceDetailResultOutputWithContext(ctx context.Context) GetInstanceDetailResultOutput {
	return o
}

func (o GetInstanceDetailResultOutput) Fields() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetInstanceDetailResult) []string { return v.Fields }).(pulumi.StringArrayOutput)
}

func (o GetInstanceDetailResultOutput) Filters() GetInstanceDetailFilterArrayOutput {
	return o.ApplyT(func(v GetInstanceDetailResult) []GetInstanceDetailFilter { return v.Filters }).(GetInstanceDetailFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetInstanceDetailResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceDetailResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetInstanceDetailResultOutput) LoadBalancerDetailSets() GetInstanceDetailLoadBalancerDetailSetArrayOutput {
	return o.ApplyT(func(v GetInstanceDetailResult) []GetInstanceDetailLoadBalancerDetailSet {
		return v.LoadBalancerDetailSets
	}).(GetInstanceDetailLoadBalancerDetailSetArrayOutput)
}

func (o GetInstanceDetailResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceDetailResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetInstanceDetailResultOutput) TargetType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceDetailResult) *string { return v.TargetType }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInstanceDetailResultOutput{})
}
