// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cat.Inputs
{

    public sealed class TaskSetBatchTasksArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("targetAddress", required: true)]
        public Input<string> TargetAddress { get; set; } = null!;

        public TaskSetBatchTasksArgs()
        {
        }
        public static new TaskSetBatchTasksArgs Empty => new TaskSetBatchTasksArgs();
    }
}
