// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dcdb

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetFileDownloadUrl(ctx *pulumi.Context, args *GetFileDownloadUrlArgs, opts ...pulumi.InvokeOption) (*GetFileDownloadUrlResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetFileDownloadUrlResult
	err := ctx.Invoke("tencentcloud:Dcdb/getFileDownloadUrl:getFileDownloadUrl", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFileDownloadUrl.
type GetFileDownloadUrlArgs struct {
	FilePath         string  `pulumi:"filePath"`
	InstanceId       string  `pulumi:"instanceId"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	ShardId          string  `pulumi:"shardId"`
}

// A collection of values returned by getFileDownloadUrl.
type GetFileDownloadUrlResult struct {
	FilePath string `pulumi:"filePath"`
	// The provider-assigned unique ID for this managed resource.
	Id               string  `pulumi:"id"`
	InstanceId       string  `pulumi:"instanceId"`
	PreSignedUrl     string  `pulumi:"preSignedUrl"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	ShardId          string  `pulumi:"shardId"`
}

func GetFileDownloadUrlOutput(ctx *pulumi.Context, args GetFileDownloadUrlOutputArgs, opts ...pulumi.InvokeOption) GetFileDownloadUrlResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetFileDownloadUrlResult, error) {
			args := v.(GetFileDownloadUrlArgs)
			r, err := GetFileDownloadUrl(ctx, &args, opts...)
			var s GetFileDownloadUrlResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetFileDownloadUrlResultOutput)
}

// A collection of arguments for invoking getFileDownloadUrl.
type GetFileDownloadUrlOutputArgs struct {
	FilePath         pulumi.StringInput    `pulumi:"filePath"`
	InstanceId       pulumi.StringInput    `pulumi:"instanceId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
	ShardId          pulumi.StringInput    `pulumi:"shardId"`
}

func (GetFileDownloadUrlOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFileDownloadUrlArgs)(nil)).Elem()
}

// A collection of values returned by getFileDownloadUrl.
type GetFileDownloadUrlResultOutput struct{ *pulumi.OutputState }

func (GetFileDownloadUrlResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFileDownloadUrlResult)(nil)).Elem()
}

func (o GetFileDownloadUrlResultOutput) ToGetFileDownloadUrlResultOutput() GetFileDownloadUrlResultOutput {
	return o
}

func (o GetFileDownloadUrlResultOutput) ToGetFileDownloadUrlResultOutputWithContext(ctx context.Context) GetFileDownloadUrlResultOutput {
	return o
}

func (o GetFileDownloadUrlResultOutput) FilePath() pulumi.StringOutput {
	return o.ApplyT(func(v GetFileDownloadUrlResult) string { return v.FilePath }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetFileDownloadUrlResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFileDownloadUrlResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetFileDownloadUrlResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetFileDownloadUrlResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetFileDownloadUrlResultOutput) PreSignedUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetFileDownloadUrlResult) string { return v.PreSignedUrl }).(pulumi.StringOutput)
}

func (o GetFileDownloadUrlResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFileDownloadUrlResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetFileDownloadUrlResultOutput) ShardId() pulumi.StringOutput {
	return o.ApplyT(func(v GetFileDownloadUrlResult) string { return v.ShardId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFileDownloadUrlResultOutput{})
}
