// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dcdb

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetShards(ctx *pulumi.Context, args *GetShardsArgs, opts ...pulumi.InvokeOption) (*GetShardsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetShardsResult
	err := ctx.Invoke("tencentcloud:Dcdb/getShards:getShards", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getShards.
type GetShardsArgs struct {
	InstanceId       string   `pulumi:"instanceId"`
	ResultOutputFile *string  `pulumi:"resultOutputFile"`
	ShardInstanceIds []string `pulumi:"shardInstanceIds"`
}

// A collection of values returned by getShards.
type GetShardsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id               string          `pulumi:"id"`
	InstanceId       string          `pulumi:"instanceId"`
	Lists            []GetShardsList `pulumi:"lists"`
	ResultOutputFile *string         `pulumi:"resultOutputFile"`
	ShardInstanceIds []string        `pulumi:"shardInstanceIds"`
}

func GetShardsOutput(ctx *pulumi.Context, args GetShardsOutputArgs, opts ...pulumi.InvokeOption) GetShardsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetShardsResult, error) {
			args := v.(GetShardsArgs)
			r, err := GetShards(ctx, &args, opts...)
			var s GetShardsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetShardsResultOutput)
}

// A collection of arguments for invoking getShards.
type GetShardsOutputArgs struct {
	InstanceId       pulumi.StringInput      `pulumi:"instanceId"`
	ResultOutputFile pulumi.StringPtrInput   `pulumi:"resultOutputFile"`
	ShardInstanceIds pulumi.StringArrayInput `pulumi:"shardInstanceIds"`
}

func (GetShardsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetShardsArgs)(nil)).Elem()
}

// A collection of values returned by getShards.
type GetShardsResultOutput struct{ *pulumi.OutputState }

func (GetShardsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetShardsResult)(nil)).Elem()
}

func (o GetShardsResultOutput) ToGetShardsResultOutput() GetShardsResultOutput {
	return o
}

func (o GetShardsResultOutput) ToGetShardsResultOutputWithContext(ctx context.Context) GetShardsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetShardsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetShardsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetShardsResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetShardsResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetShardsResultOutput) Lists() GetShardsListArrayOutput {
	return o.ApplyT(func(v GetShardsResult) []GetShardsList { return v.Lists }).(GetShardsListArrayOutput)
}

func (o GetShardsResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetShardsResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetShardsResultOutput) ShardInstanceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetShardsResult) []string { return v.ShardInstanceIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetShardsResultOutput{})
}
