// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Ckafka.Inputs
{

    public sealed class DatahubTaskTransformParamFailureParamTopicParamGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("compressionType")]
        public Input<string>? CompressionType { get; set; }

        [Input("msgMultiple")]
        public Input<int>? MsgMultiple { get; set; }

        [Input("offsetType")]
        public Input<string>? OffsetType { get; set; }

        [Input("resource", required: true)]
        public Input<string> Resource { get; set; } = null!;

        [Input("startTime")]
        public Input<int>? StartTime { get; set; }

        [Input("topicId")]
        public Input<string>? TopicId { get; set; }

        [Input("useAutoCreateTopic")]
        public Input<bool>? UseAutoCreateTopic { get; set; }

        public DatahubTaskTransformParamFailureParamTopicParamGetArgs()
        {
        }
        public static new DatahubTaskTransformParamFailureParamTopicParamGetArgs Empty => new DatahubTaskTransformParamFailureParamTopicParamGetArgs();
    }
}
