// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getClusterInstances(args: GetClusterInstancesArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterInstancesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Deprecatedcontainer/getClusterInstances:getClusterInstances", {
        "clusterId": args.clusterId,
        "limit": args.limit,
    }, opts);
}

/**
 * A collection of arguments for invoking getClusterInstances.
 */
export interface GetClusterInstancesArgs {
    clusterId: string;
    limit?: number;
}

/**
 * A collection of values returned by getClusterInstances.
 */
export interface GetClusterInstancesResult {
    readonly clusterId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly limit?: number;
    readonly nodes: outputs.Deprecatedcontainer.GetClusterInstancesNode[];
    readonly totalCount: number;
}
export function getClusterInstancesOutput(args: GetClusterInstancesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetClusterInstancesResult> {
    return pulumi.output(args).apply((a: any) => getClusterInstances(a, opts))
}

/**
 * A collection of arguments for invoking getClusterInstances.
 */
export interface GetClusterInstancesOutputArgs {
    clusterId: pulumi.Input<string>;
    limit?: pulumi.Input<number>;
}
