# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetInstanceConfigsConfigListResult',
    'GetInstancesReservedInstanceListResult',
]

@pulumi.output_type
class GetInstanceConfigsConfigListResult(dict):
    def __init__(__self__, *,
                 availability_zone: str,
                 config_id: str,
                 currency_code: str,
                 duration: int,
                 instance_type: str,
                 offering_type: str,
                 platform: str,
                 price: float,
                 usage_price: float):
        pulumi.set(__self__, "availability_zone", availability_zone)
        pulumi.set(__self__, "config_id", config_id)
        pulumi.set(__self__, "currency_code", currency_code)
        pulumi.set(__self__, "duration", duration)
        pulumi.set(__self__, "instance_type", instance_type)
        pulumi.set(__self__, "offering_type", offering_type)
        pulumi.set(__self__, "platform", platform)
        pulumi.set(__self__, "price", price)
        pulumi.set(__self__, "usage_price", usage_price)

    @property
    @pulumi.getter(name="availabilityZone")
    def availability_zone(self) -> str:
        return pulumi.get(self, "availability_zone")

    @property
    @pulumi.getter(name="configId")
    def config_id(self) -> str:
        return pulumi.get(self, "config_id")

    @property
    @pulumi.getter(name="currencyCode")
    def currency_code(self) -> str:
        return pulumi.get(self, "currency_code")

    @property
    @pulumi.getter
    def duration(self) -> int:
        return pulumi.get(self, "duration")

    @property
    @pulumi.getter(name="instanceType")
    def instance_type(self) -> str:
        return pulumi.get(self, "instance_type")

    @property
    @pulumi.getter(name="offeringType")
    def offering_type(self) -> str:
        return pulumi.get(self, "offering_type")

    @property
    @pulumi.getter
    def platform(self) -> str:
        return pulumi.get(self, "platform")

    @property
    @pulumi.getter
    def price(self) -> float:
        return pulumi.get(self, "price")

    @property
    @pulumi.getter(name="usagePrice")
    def usage_price(self) -> float:
        return pulumi.get(self, "usage_price")


@pulumi.output_type
class GetInstancesReservedInstanceListResult(dict):
    def __init__(__self__, *,
                 availability_zone: str,
                 end_time: str,
                 instance_count: int,
                 instance_type: str,
                 reserved_instance_id: str,
                 start_time: str,
                 status: str):
        pulumi.set(__self__, "availability_zone", availability_zone)
        pulumi.set(__self__, "end_time", end_time)
        pulumi.set(__self__, "instance_count", instance_count)
        pulumi.set(__self__, "instance_type", instance_type)
        pulumi.set(__self__, "reserved_instance_id", reserved_instance_id)
        pulumi.set(__self__, "start_time", start_time)
        pulumi.set(__self__, "status", status)

    @property
    @pulumi.getter(name="availabilityZone")
    def availability_zone(self) -> str:
        return pulumi.get(self, "availability_zone")

    @property
    @pulumi.getter(name="endTime")
    def end_time(self) -> str:
        return pulumi.get(self, "end_time")

    @property
    @pulumi.getter(name="instanceCount")
    def instance_count(self) -> int:
        return pulumi.get(self, "instance_count")

    @property
    @pulumi.getter(name="instanceType")
    def instance_type(self) -> str:
        return pulumi.get(self, "instance_type")

    @property
    @pulumi.getter(name="reservedInstanceId")
    def reserved_instance_id(self) -> str:
        return pulumi.get(self, "reserved_instance_id")

    @property
    @pulumi.getter(name="startTime")
    def start_time(self) -> str:
        return pulumi.get(self, "start_time")

    @property
    @pulumi.getter
    def status(self) -> str:
        return pulumi.get(self, "status")


