// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cfs.Outputs
{

    [OutputType]
    public sealed class GetAvailableZoneRegionZoneZoneTypeProtocolResult
    {
        public readonly string Protocol;
        public readonly string SaleStatus;

        [OutputConstructor]
        private GetAvailableZoneRegionZoneZoneTypeProtocolResult(
            string protocol,

            string saleStatus)
        {
            Protocol = protocol;
            SaleStatus = saleStatus;
        }
    }
}
