// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tse.Outputs
{

    [OutputType]
    public sealed class GetGatewayServicesResultServiceListResult
    {
        public readonly string CreatedTime;
        public readonly bool Editable;
        public readonly string Id;
        public readonly string Name;
        public readonly ImmutableArray<string> Tags;
        public readonly ImmutableArray<Outputs.GetGatewayServicesResultServiceListUpstreamInfoResult> UpstreamInfos;
        public readonly string UpstreamType;

        [OutputConstructor]
        private GetGatewayServicesResultServiceListResult(
            string createdTime,

            bool editable,

            string id,

            string name,

            ImmutableArray<string> tags,

            ImmutableArray<Outputs.GetGatewayServicesResultServiceListUpstreamInfoResult> upstreamInfos,

            string upstreamType)
        {
            CreatedTime = createdTime;
            Editable = editable;
            Id = id;
            Name = name;
            Tags = tags;
            UpstreamInfos = upstreamInfos;
            UpstreamType = upstreamType;
        }
    }
}
