// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cos.Inputs
{

    public sealed class BatchOperationArgs : global::Pulumi.ResourceArgs
    {
        [Input("cosInitiateRestoreObject")]
        public Input<Inputs.BatchOperationCosInitiateRestoreObjectArgs>? CosInitiateRestoreObject { get; set; }

        [Input("cosPutObjectCopy")]
        public Input<Inputs.BatchOperationCosPutObjectCopyArgs>? CosPutObjectCopy { get; set; }

        public BatchOperationArgs()
        {
        }
        public static new BatchOperationArgs Empty => new BatchOperationArgs();
    }
}
