// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dayu

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetL7RulesV2(ctx *pulumi.Context, args *GetL7RulesV2Args, opts ...pulumi.InvokeOption) (*GetL7RulesV2Result, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetL7RulesV2Result
	err := ctx.Invoke("tencentcloud:Dayu/getL7RulesV2:getL7RulesV2", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getL7RulesV2.
type GetL7RulesV2Args struct {
	Business string  `pulumi:"business"`
	Domain   *string `pulumi:"domain"`
	Ip       *string `pulumi:"ip"`
	// Deprecated: It has been deprecated from version 1.81.21.
	Limit *int `pulumi:"limit"`
	// Deprecated: It has been deprecated from version 1.81.21.
	Offset           *int    `pulumi:"offset"`
	Protocol         *string `pulumi:"protocol"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getL7RulesV2.
type GetL7RulesV2Result struct {
	Business string  `pulumi:"business"`
	Domain   *string `pulumi:"domain"`
	// The provider-assigned unique ID for this managed resource.
	Id string  `pulumi:"id"`
	Ip *string `pulumi:"ip"`
	// Deprecated: It has been deprecated from version 1.81.21.
	Limit *int               `pulumi:"limit"`
	Lists []GetL7RulesV2List `pulumi:"lists"`
	// Deprecated: It has been deprecated from version 1.81.21.
	Offset           *int    `pulumi:"offset"`
	Protocol         *string `pulumi:"protocol"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

func GetL7RulesV2Output(ctx *pulumi.Context, args GetL7RulesV2OutputArgs, opts ...pulumi.InvokeOption) GetL7RulesV2ResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetL7RulesV2Result, error) {
			args := v.(GetL7RulesV2Args)
			r, err := GetL7RulesV2(ctx, &args, opts...)
			var s GetL7RulesV2Result
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetL7RulesV2ResultOutput)
}

// A collection of arguments for invoking getL7RulesV2.
type GetL7RulesV2OutputArgs struct {
	Business pulumi.StringInput    `pulumi:"business"`
	Domain   pulumi.StringPtrInput `pulumi:"domain"`
	Ip       pulumi.StringPtrInput `pulumi:"ip"`
	// Deprecated: It has been deprecated from version 1.81.21.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
	// Deprecated: It has been deprecated from version 1.81.21.
	Offset           pulumi.IntPtrInput    `pulumi:"offset"`
	Protocol         pulumi.StringPtrInput `pulumi:"protocol"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetL7RulesV2OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetL7RulesV2Args)(nil)).Elem()
}

// A collection of values returned by getL7RulesV2.
type GetL7RulesV2ResultOutput struct{ *pulumi.OutputState }

func (GetL7RulesV2ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetL7RulesV2Result)(nil)).Elem()
}

func (o GetL7RulesV2ResultOutput) ToGetL7RulesV2ResultOutput() GetL7RulesV2ResultOutput {
	return o
}

func (o GetL7RulesV2ResultOutput) ToGetL7RulesV2ResultOutputWithContext(ctx context.Context) GetL7RulesV2ResultOutput {
	return o
}

func (o GetL7RulesV2ResultOutput) Business() pulumi.StringOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) string { return v.Business }).(pulumi.StringOutput)
}

func (o GetL7RulesV2ResultOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) *string { return v.Domain }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetL7RulesV2ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetL7RulesV2ResultOutput) Ip() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) *string { return v.Ip }).(pulumi.StringPtrOutput)
}

// Deprecated: It has been deprecated from version 1.81.21.
func (o GetL7RulesV2ResultOutput) Limit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) *int { return v.Limit }).(pulumi.IntPtrOutput)
}

func (o GetL7RulesV2ResultOutput) Lists() GetL7RulesV2ListArrayOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) []GetL7RulesV2List { return v.Lists }).(GetL7RulesV2ListArrayOutput)
}

// Deprecated: It has been deprecated from version 1.81.21.
func (o GetL7RulesV2ResultOutput) Offset() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) *int { return v.Offset }).(pulumi.IntPtrOutput)
}

func (o GetL7RulesV2ResultOutput) Protocol() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) *string { return v.Protocol }).(pulumi.StringPtrOutput)
}

func (o GetL7RulesV2ResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetL7RulesV2Result) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetL7RulesV2ResultOutput{})
}
