// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class EncryptionProtection extends pulumi.CustomResource {
    /**
     * Get an existing EncryptionProtection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EncryptionProtectionState, opts?: pulumi.CustomResourceOptions): EncryptionProtection {
        return new EncryptionProtection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tencentcloud:Kubernetes/encryptionProtection:EncryptionProtection';

    /**
     * Returns true if the given object is an instance of EncryptionProtection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EncryptionProtection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EncryptionProtection.__pulumiType;
    }

    /**
     * cluster id.
     */
    public readonly clusterId!: pulumi.Output<string>;
    /**
     * kms encryption configuration.
     */
    public readonly kmsConfiguration!: pulumi.Output<outputs.Kubernetes.EncryptionProtectionKmsConfiguration>;
    /**
     * kms encryption status.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;

    /**
     * Create a EncryptionProtection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EncryptionProtectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EncryptionProtectionArgs | EncryptionProtectionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EncryptionProtectionState | undefined;
            resourceInputs["clusterId"] = state ? state.clusterId : undefined;
            resourceInputs["kmsConfiguration"] = state ? state.kmsConfiguration : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
        } else {
            const args = argsOrState as EncryptionProtectionArgs | undefined;
            if ((!args || args.clusterId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            if ((!args || args.kmsConfiguration === undefined) && !opts.urn) {
                throw new Error("Missing required property 'kmsConfiguration'");
            }
            resourceInputs["clusterId"] = args ? args.clusterId : undefined;
            resourceInputs["kmsConfiguration"] = args ? args.kmsConfiguration : undefined;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EncryptionProtection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EncryptionProtection resources.
 */
export interface EncryptionProtectionState {
    /**
     * cluster id.
     */
    clusterId?: pulumi.Input<string>;
    /**
     * kms encryption configuration.
     */
    kmsConfiguration?: pulumi.Input<inputs.Kubernetes.EncryptionProtectionKmsConfiguration>;
    /**
     * kms encryption status.
     */
    status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EncryptionProtection resource.
 */
export interface EncryptionProtectionArgs {
    /**
     * cluster id.
     */
    clusterId: pulumi.Input<string>;
    /**
     * kms encryption configuration.
     */
    kmsConfiguration: pulumi.Input<inputs.Kubernetes.EncryptionProtectionKmsConfiguration>;
}
