// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Ci.Inputs
{

    public sealed class MediaSpeechRecognitionTemplateSpeechRecognitionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("channelNum", required: true)]
        public Input<string> ChannelNum { get; set; } = null!;

        [Input("convertNumMode")]
        public Input<string>? ConvertNumMode { get; set; }

        [Input("engineModelType", required: true)]
        public Input<string> EngineModelType { get; set; } = null!;

        [Input("filterDirty")]
        public Input<string>? FilterDirty { get; set; }

        [Input("filterModal")]
        public Input<string>? FilterModal { get; set; }

        [Input("filterPunc")]
        public Input<string>? FilterPunc { get; set; }

        [Input("outputFileType")]
        public Input<string>? OutputFileType { get; set; }

        [Input("resTextFormat")]
        public Input<string>? ResTextFormat { get; set; }

        [Input("speakerDiarization")]
        public Input<string>? SpeakerDiarization { get; set; }

        [Input("speakerNumber")]
        public Input<string>? SpeakerNumber { get; set; }

        public MediaSpeechRecognitionTemplateSpeechRecognitionGetArgs()
        {
        }
        public static new MediaSpeechRecognitionTemplateSpeechRecognitionGetArgs Empty => new MediaSpeechRecognitionTemplateSpeechRecognitionGetArgs();
    }
}
