// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tsf.Outputs
{

    [OutputType]
    public sealed class GetApplicationPublicConfigResultContentResult
    {
        public readonly string ApplicationId;
        public readonly string ApplicationName;
        public readonly string ConfigId;
        public readonly string ConfigName;
        public readonly string ConfigType;
        public readonly string ConfigValue;
        public readonly string ConfigVersion;
        public readonly int ConfigVersionCount;
        public readonly string ConfigVersionDesc;
        public readonly string CreationTime;
        public readonly bool DeleteFlag;
        public readonly string LastUpdateTime;

        [OutputConstructor]
        private GetApplicationPublicConfigResultContentResult(
            string applicationId,

            string applicationName,

            string configId,

            string configName,

            string configType,

            string configValue,

            string configVersion,

            int configVersionCount,

            string configVersionDesc,

            string creationTime,

            bool deleteFlag,

            string lastUpdateTime)
        {
            ApplicationId = applicationId;
            ApplicationName = applicationName;
            ConfigId = configId;
            ConfigName = configName;
            ConfigType = configType;
            ConfigValue = configValue;
            ConfigVersion = configVersion;
            ConfigVersionCount = configVersionCount;
            ConfigVersionDesc = configVersionDesc;
            CreationTime = creationTime;
            DeleteFlag = deleteFlag;
            LastUpdateTime = lastUpdateTime;
        }
    }
}
