// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tsf.Outputs
{

    [OutputType]
    public sealed class GetApplicationConfigResultResult
    {
        public readonly ImmutableArray<Outputs.GetApplicationConfigResultContentResult> Contents;
        public readonly int TotalCount;

        [OutputConstructor]
        private GetApplicationConfigResultResult(
            ImmutableArray<Outputs.GetApplicationConfigResultContentResult> contents,

            int totalCount)
        {
            Contents = contents;
            TotalCount = totalCount;
        }
    }
}
