// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tsf.Outputs
{

    [OutputType]
    public sealed class UnitRuleUnitRuleItemList
    {
        public readonly string? Description;
        public readonly string DestNamespaceId;
        public readonly string DestNamespaceName;
        public readonly string Name;
        public readonly int? Priority;
        public readonly string Relationship;
        public readonly string? RuleId;
        public readonly string? UnitRuleId;
        public readonly ImmutableArray<Outputs.UnitRuleUnitRuleItemListUnitRuleTagList> UnitRuleTagLists;

        [OutputConstructor]
        private UnitRuleUnitRuleItemList(
            string? description,

            string destNamespaceId,

            string destNamespaceName,

            string name,

            int? priority,

            string relationship,

            string? ruleId,

            string? unitRuleId,

            ImmutableArray<Outputs.UnitRuleUnitRuleItemListUnitRuleTagList> unitRuleTagLists)
        {
            Description = description;
            DestNamespaceId = destNamespaceId;
            DestNamespaceName = destNamespaceName;
            Name = name;
            Priority = priority;
            Relationship = relationship;
            RuleId = ruleId;
            UnitRuleId = unitRuleId;
            UnitRuleTagLists = unitRuleTagLists;
        }
    }
}
