// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Rum.Outputs
{

    [OutputType]
    public sealed class GetWhitelistWhitelistSetResult
    {
        public readonly string Aid;
        public readonly string CreateTime;
        public readonly string CreateUser;
        public readonly string Remark;
        public readonly string Ttl;
        public readonly string WhitelistUin;
        public readonly string Wid;

        [OutputConstructor]
        private GetWhitelistWhitelistSetResult(
            string aid,

            string createTime,

            string createUser,

            string remark,

            string ttl,

            string whitelistUin,

            string wid)
        {
            Aid = aid;
            CreateTime = createTime;
            CreateUser = createUser;
            Remark = remark;
            Ttl = ttl;
            WhitelistUin = whitelistUin;
            Wid = wid;
        }
    }
}
