// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Clickhouse.Outputs
{

    [OutputType]
    public sealed class BackupStrategyMetaBackupStrategy
    {
        public readonly int? ExecuteHour;
        public readonly int? RetainDays;
        public readonly string? WeekDays;

        [OutputConstructor]
        private BackupStrategyMetaBackupStrategy(
            int? executeHour,

            int? retainDays,

            string? weekDays)
        {
            ExecuteHour = executeHour;
            RetainDays = retainDays;
            WeekDays = weekDays;
        }
    }
}
