// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Pts.Inputs
{

    public sealed class ScenarioLoadArgs : global::Pulumi.ResourceArgs
    {
        [Input("geoRegionsLoadDistributions")]
        private InputList<Inputs.ScenarioLoadGeoRegionsLoadDistributionArgs>? _geoRegionsLoadDistributions;
        public InputList<Inputs.ScenarioLoadGeoRegionsLoadDistributionArgs> GeoRegionsLoadDistributions
        {
            get => _geoRegionsLoadDistributions ?? (_geoRegionsLoadDistributions = new InputList<Inputs.ScenarioLoadGeoRegionsLoadDistributionArgs>());
            set => _geoRegionsLoadDistributions = value;
        }

        [Input("loadSpec")]
        public Input<Inputs.ScenarioLoadLoadSpecArgs>? LoadSpec { get; set; }

        [Input("vpcLoadDistribution")]
        public Input<Inputs.ScenarioLoadVpcLoadDistributionArgs>? VpcLoadDistribution { get; set; }

        public ScenarioLoadArgs()
        {
        }
        public static new ScenarioLoadArgs Empty => new ScenarioLoadArgs();
    }
}
