// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Kubernetes
{
    public static class GetClusterAuthenticationOptions
    {
        public static Task<GetClusterAuthenticationOptionsResult> InvokeAsync(GetClusterAuthenticationOptionsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetClusterAuthenticationOptionsResult>("tencentcloud:Kubernetes/getClusterAuthenticationOptions:getClusterAuthenticationOptions", args ?? new GetClusterAuthenticationOptionsArgs(), options.WithDefaults());

        public static Output<GetClusterAuthenticationOptionsResult> Invoke(GetClusterAuthenticationOptionsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetClusterAuthenticationOptionsResult>("tencentcloud:Kubernetes/getClusterAuthenticationOptions:getClusterAuthenticationOptions", args ?? new GetClusterAuthenticationOptionsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetClusterAuthenticationOptionsArgs : global::Pulumi.InvokeArgs
    {
        [Input("clusterId", required: true)]
        public string ClusterId { get; set; } = null!;

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetClusterAuthenticationOptionsArgs()
        {
        }
        public static new GetClusterAuthenticationOptionsArgs Empty => new GetClusterAuthenticationOptionsArgs();
    }

    public sealed class GetClusterAuthenticationOptionsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetClusterAuthenticationOptionsInvokeArgs()
        {
        }
        public static new GetClusterAuthenticationOptionsInvokeArgs Empty => new GetClusterAuthenticationOptionsInvokeArgs();
    }


    [OutputType]
    public sealed class GetClusterAuthenticationOptionsResult
    {
        public readonly string ClusterId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string LatestOperationState;
        public readonly ImmutableArray<Outputs.GetClusterAuthenticationOptionsOidcConfigResult> OidcConfigs;
        public readonly string? ResultOutputFile;
        public readonly ImmutableArray<Outputs.GetClusterAuthenticationOptionsServiceAccountResult> ServiceAccounts;

        [OutputConstructor]
        private GetClusterAuthenticationOptionsResult(
            string clusterId,

            string id,

            string latestOperationState,

            ImmutableArray<Outputs.GetClusterAuthenticationOptionsOidcConfigResult> oidcConfigs,

            string? resultOutputFile,

            ImmutableArray<Outputs.GetClusterAuthenticationOptionsServiceAccountResult> serviceAccounts)
        {
            ClusterId = clusterId;
            Id = id;
            LatestOperationState = latestOperationState;
            OidcConfigs = oidcConfigs;
            ResultOutputFile = resultOutputFile;
            ServiceAccounts = serviceAccounts;
        }
    }
}
