// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redis

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetParamRecords(ctx *pulumi.Context, args *GetParamRecordsArgs, opts ...pulumi.InvokeOption) (*GetParamRecordsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetParamRecordsResult
	err := ctx.Invoke("tencentcloud:Redis/getParamRecords:getParamRecords", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getParamRecords.
type GetParamRecordsArgs struct {
	InstanceId       string  `pulumi:"instanceId"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getParamRecords.
type GetParamRecordsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                     string                                `pulumi:"id"`
	InstanceId             string                                `pulumi:"instanceId"`
	InstanceParamHistories []GetParamRecordsInstanceParamHistory `pulumi:"instanceParamHistories"`
	ResultOutputFile       *string                               `pulumi:"resultOutputFile"`
}

func GetParamRecordsOutput(ctx *pulumi.Context, args GetParamRecordsOutputArgs, opts ...pulumi.InvokeOption) GetParamRecordsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetParamRecordsResult, error) {
			args := v.(GetParamRecordsArgs)
			r, err := GetParamRecords(ctx, &args, opts...)
			var s GetParamRecordsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetParamRecordsResultOutput)
}

// A collection of arguments for invoking getParamRecords.
type GetParamRecordsOutputArgs struct {
	InstanceId       pulumi.StringInput    `pulumi:"instanceId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetParamRecordsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetParamRecordsArgs)(nil)).Elem()
}

// A collection of values returned by getParamRecords.
type GetParamRecordsResultOutput struct{ *pulumi.OutputState }

func (GetParamRecordsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetParamRecordsResult)(nil)).Elem()
}

func (o GetParamRecordsResultOutput) ToGetParamRecordsResultOutput() GetParamRecordsResultOutput {
	return o
}

func (o GetParamRecordsResultOutput) ToGetParamRecordsResultOutputWithContext(ctx context.Context) GetParamRecordsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetParamRecordsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetParamRecordsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetParamRecordsResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetParamRecordsResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetParamRecordsResultOutput) InstanceParamHistories() GetParamRecordsInstanceParamHistoryArrayOutput {
	return o.ApplyT(func(v GetParamRecordsResult) []GetParamRecordsInstanceParamHistory { return v.InstanceParamHistories }).(GetParamRecordsInstanceParamHistoryArrayOutput)
}

func (o GetParamRecordsResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetParamRecordsResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetParamRecordsResultOutput{})
}
