// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tsf
{
    public static class GetApplication
    {
        public static Task<GetApplicationResult> InvokeAsync(GetApplicationArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetApplicationResult>("tencentcloud:Tsf/getApplication:getApplication", args ?? new GetApplicationArgs(), options.WithDefaults());

        public static Output<GetApplicationResult> Invoke(GetApplicationInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetApplicationResult>("tencentcloud:Tsf/getApplication:getApplication", args ?? new GetApplicationInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetApplicationArgs : global::Pulumi.InvokeArgs
    {
        [Input("applicationIdLists")]
        private List<string>? _applicationIdLists;
        public List<string> ApplicationIdLists
        {
            get => _applicationIdLists ?? (_applicationIdLists = new List<string>());
            set => _applicationIdLists = value;
        }

        [Input("applicationResourceTypeLists")]
        private List<string>? _applicationResourceTypeLists;
        public List<string> ApplicationResourceTypeLists
        {
            get => _applicationResourceTypeLists ?? (_applicationResourceTypeLists = new List<string>());
            set => _applicationResourceTypeLists = value;
        }

        [Input("applicationType")]
        public string? ApplicationType { get; set; }

        [Input("microserviceType")]
        public string? MicroserviceType { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetApplicationArgs()
        {
        }
        public static new GetApplicationArgs Empty => new GetApplicationArgs();
    }

    public sealed class GetApplicationInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("applicationIdLists")]
        private InputList<string>? _applicationIdLists;
        public InputList<string> ApplicationIdLists
        {
            get => _applicationIdLists ?? (_applicationIdLists = new InputList<string>());
            set => _applicationIdLists = value;
        }

        [Input("applicationResourceTypeLists")]
        private InputList<string>? _applicationResourceTypeLists;
        public InputList<string> ApplicationResourceTypeLists
        {
            get => _applicationResourceTypeLists ?? (_applicationResourceTypeLists = new InputList<string>());
            set => _applicationResourceTypeLists = value;
        }

        [Input("applicationType")]
        public Input<string>? ApplicationType { get; set; }

        [Input("microserviceType")]
        public Input<string>? MicroserviceType { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetApplicationInvokeArgs()
        {
        }
        public static new GetApplicationInvokeArgs Empty => new GetApplicationInvokeArgs();
    }


    [OutputType]
    public sealed class GetApplicationResult
    {
        public readonly ImmutableArray<string> ApplicationIdLists;
        public readonly ImmutableArray<string> ApplicationResourceTypeLists;
        public readonly string? ApplicationType;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? MicroserviceType;
        public readonly string? ResultOutputFile;
        public readonly ImmutableArray<Outputs.GetApplicationResultResult> Results;

        [OutputConstructor]
        private GetApplicationResult(
            ImmutableArray<string> applicationIdLists,

            ImmutableArray<string> applicationResourceTypeLists,

            string? applicationType,

            string id,

            string? microserviceType,

            string? resultOutputFile,

            ImmutableArray<Outputs.GetApplicationResultResult> results)
        {
            ApplicationIdLists = applicationIdLists;
            ApplicationResourceTypeLists = applicationResourceTypeLists;
            ApplicationType = applicationType;
            Id = id;
            MicroserviceType = microserviceType;
            ResultOutputFile = resultOutputFile;
            Results = results;
        }
    }
}
