// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package images

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInstance(ctx *pulumi.Context, args *GetInstanceArgs, opts ...pulumi.InvokeOption) (*GetInstanceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInstanceResult
	err := ctx.Invoke("tencentcloud:Images/getInstance:getInstance", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstance.
type GetInstanceArgs struct {
	ImageId          *string  `pulumi:"imageId"`
	ImageNameRegex   *string  `pulumi:"imageNameRegex"`
	ImageTypes       []string `pulumi:"imageTypes"`
	InstanceType     *string  `pulumi:"instanceType"`
	OsName           *string  `pulumi:"osName"`
	ResultOutputFile *string  `pulumi:"resultOutputFile"`
}

// A collection of values returned by getInstance.
type GetInstanceResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id               string             `pulumi:"id"`
	ImageId          *string            `pulumi:"imageId"`
	ImageNameRegex   *string            `pulumi:"imageNameRegex"`
	ImageTypes       []string           `pulumi:"imageTypes"`
	Images           []GetInstanceImage `pulumi:"images"`
	InstanceType     *string            `pulumi:"instanceType"`
	OsName           *string            `pulumi:"osName"`
	ResultOutputFile *string            `pulumi:"resultOutputFile"`
}

func GetInstanceOutput(ctx *pulumi.Context, args GetInstanceOutputArgs, opts ...pulumi.InvokeOption) GetInstanceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetInstanceResult, error) {
			args := v.(GetInstanceArgs)
			r, err := GetInstance(ctx, &args, opts...)
			var s GetInstanceResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetInstanceResultOutput)
}

// A collection of arguments for invoking getInstance.
type GetInstanceOutputArgs struct {
	ImageId          pulumi.StringPtrInput   `pulumi:"imageId"`
	ImageNameRegex   pulumi.StringPtrInput   `pulumi:"imageNameRegex"`
	ImageTypes       pulumi.StringArrayInput `pulumi:"imageTypes"`
	InstanceType     pulumi.StringPtrInput   `pulumi:"instanceType"`
	OsName           pulumi.StringPtrInput   `pulumi:"osName"`
	ResultOutputFile pulumi.StringPtrInput   `pulumi:"resultOutputFile"`
}

func (GetInstanceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceArgs)(nil)).Elem()
}

// A collection of values returned by getInstance.
type GetInstanceResultOutput struct{ *pulumi.OutputState }

func (GetInstanceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceResult)(nil)).Elem()
}

func (o GetInstanceResultOutput) ToGetInstanceResultOutput() GetInstanceResultOutput {
	return o
}

func (o GetInstanceResultOutput) ToGetInstanceResultOutputWithContext(ctx context.Context) GetInstanceResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetInstanceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) ImageId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceResult) *string { return v.ImageId }).(pulumi.StringPtrOutput)
}

func (o GetInstanceResultOutput) ImageNameRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceResult) *string { return v.ImageNameRegex }).(pulumi.StringPtrOutput)
}

func (o GetInstanceResultOutput) ImageTypes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetInstanceResult) []string { return v.ImageTypes }).(pulumi.StringArrayOutput)
}

func (o GetInstanceResultOutput) Images() GetInstanceImageArrayOutput {
	return o.ApplyT(func(v GetInstanceResult) []GetInstanceImage { return v.Images }).(GetInstanceImageArrayOutput)
}

func (o GetInstanceResultOutput) InstanceType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceResult) *string { return v.InstanceType }).(pulumi.StringPtrOutput)
}

func (o GetInstanceResultOutput) OsName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceResult) *string { return v.OsName }).(pulumi.StringPtrOutput)
}

func (o GetInstanceResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInstanceResultOutput{})
}
