// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mysql
{
    public static class GetProjectSecurityGroup
    {
        public static Task<GetProjectSecurityGroupResult> InvokeAsync(GetProjectSecurityGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetProjectSecurityGroupResult>("tencentcloud:Mysql/getProjectSecurityGroup:getProjectSecurityGroup", args ?? new GetProjectSecurityGroupArgs(), options.WithDefaults());

        public static Output<GetProjectSecurityGroupResult> Invoke(GetProjectSecurityGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetProjectSecurityGroupResult>("tencentcloud:Mysql/getProjectSecurityGroup:getProjectSecurityGroup", args ?? new GetProjectSecurityGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetProjectSecurityGroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("projectId")]
        public int? ProjectId { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetProjectSecurityGroupArgs()
        {
        }
        public static new GetProjectSecurityGroupArgs Empty => new GetProjectSecurityGroupArgs();
    }

    public sealed class GetProjectSecurityGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("projectId")]
        public Input<int>? ProjectId { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetProjectSecurityGroupInvokeArgs()
        {
        }
        public static new GetProjectSecurityGroupInvokeArgs Empty => new GetProjectSecurityGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetProjectSecurityGroupResult
    {
        public readonly ImmutableArray<Outputs.GetProjectSecurityGroupGroupResult> Groups;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int? ProjectId;
        public readonly string? ResultOutputFile;

        [OutputConstructor]
        private GetProjectSecurityGroupResult(
            ImmutableArray<Outputs.GetProjectSecurityGroupGroupResult> groups,

            string id,

            int? projectId,

            string? resultOutputFile)
        {
            Groups = groups;
            Id = id;
            ProjectId = projectId;
            ResultOutputFile = resultOutputFile;
        }
    }
}
