// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mysql
{
    public static class GetSlowLogData
    {
        public static Task<GetSlowLogDataResult> InvokeAsync(GetSlowLogDataArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSlowLogDataResult>("tencentcloud:Mysql/getSlowLogData:getSlowLogData", args ?? new GetSlowLogDataArgs(), options.WithDefaults());

        public static Output<GetSlowLogDataResult> Invoke(GetSlowLogDataInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSlowLogDataResult>("tencentcloud:Mysql/getSlowLogData:getSlowLogData", args ?? new GetSlowLogDataInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSlowLogDataArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataBases")]
        private List<string>? _dataBases;
        public List<string> DataBases
        {
            get => _dataBases ?? (_dataBases = new List<string>());
            set => _dataBases = value;
        }

        [Input("endTime", required: true)]
        public int EndTime { get; set; }

        [Input("instType")]
        public string? InstType { get; set; }

        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        [Input("orderBy")]
        public string? OrderBy { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        [Input("sortBy")]
        public string? SortBy { get; set; }

        [Input("startTime", required: true)]
        public int StartTime { get; set; }

        [Input("userHosts")]
        private List<string>? _userHosts;
        public List<string> UserHosts
        {
            get => _userHosts ?? (_userHosts = new List<string>());
            set => _userHosts = value;
        }

        [Input("userNames")]
        private List<string>? _userNames;
        public List<string> UserNames
        {
            get => _userNames ?? (_userNames = new List<string>());
            set => _userNames = value;
        }

        public GetSlowLogDataArgs()
        {
        }
        public static new GetSlowLogDataArgs Empty => new GetSlowLogDataArgs();
    }

    public sealed class GetSlowLogDataInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataBases")]
        private InputList<string>? _dataBases;
        public InputList<string> DataBases
        {
            get => _dataBases ?? (_dataBases = new InputList<string>());
            set => _dataBases = value;
        }

        [Input("endTime", required: true)]
        public Input<int> EndTime { get; set; } = null!;

        [Input("instType")]
        public Input<string>? InstType { get; set; }

        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("orderBy")]
        public Input<string>? OrderBy { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        [Input("sortBy")]
        public Input<string>? SortBy { get; set; }

        [Input("startTime", required: true)]
        public Input<int> StartTime { get; set; } = null!;

        [Input("userHosts")]
        private InputList<string>? _userHosts;
        public InputList<string> UserHosts
        {
            get => _userHosts ?? (_userHosts = new InputList<string>());
            set => _userHosts = value;
        }

        [Input("userNames")]
        private InputList<string>? _userNames;
        public InputList<string> UserNames
        {
            get => _userNames ?? (_userNames = new InputList<string>());
            set => _userNames = value;
        }

        public GetSlowLogDataInvokeArgs()
        {
        }
        public static new GetSlowLogDataInvokeArgs Empty => new GetSlowLogDataInvokeArgs();
    }


    [OutputType]
    public sealed class GetSlowLogDataResult
    {
        public readonly ImmutableArray<string> DataBases;
        public readonly int EndTime;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? InstType;
        public readonly string InstanceId;
        public readonly ImmutableArray<Outputs.GetSlowLogDataItemResult> Items;
        public readonly string? OrderBy;
        public readonly string? ResultOutputFile;
        public readonly string? SortBy;
        public readonly int StartTime;
        public readonly ImmutableArray<string> UserHosts;
        public readonly ImmutableArray<string> UserNames;

        [OutputConstructor]
        private GetSlowLogDataResult(
            ImmutableArray<string> dataBases,

            int endTime,

            string id,

            string? instType,

            string instanceId,

            ImmutableArray<Outputs.GetSlowLogDataItemResult> items,

            string? orderBy,

            string? resultOutputFile,

            string? sortBy,

            int startTime,

            ImmutableArray<string> userHosts,

            ImmutableArray<string> userNames)
        {
            DataBases = dataBases;
            EndTime = endTime;
            Id = id;
            InstType = instType;
            InstanceId = instanceId;
            Items = items;
            OrderBy = orderBy;
            ResultOutputFile = resultOutputFile;
            SortBy = sortBy;
            StartTime = startTime;
            UserHosts = userHosts;
            UserNames = userNames;
        }
    }
}
