// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cos.Outputs
{

    [OutputType]
    public sealed class BatchManifestSpec
    {
        public readonly ImmutableArray<string> Fields;
        public readonly string Format;

        [OutputConstructor]
        private BatchManifestSpec(
            ImmutableArray<string> fields,

            string format)
        {
            Fields = fields;
            Format = format;
        }
    }
}
