// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getGroups(args?: GetGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetGroupsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Tsf/getGroups:getGroups", {
        "applicationId": args.applicationId,
        "clusterId": args.clusterId,
        "groupIdLists": args.groupIdLists,
        "groupResourceTypeLists": args.groupResourceTypeLists,
        "namespaceId": args.namespaceId,
        "orderBy": args.orderBy,
        "orderType": args.orderType,
        "resultOutputFile": args.resultOutputFile,
        "searchWord": args.searchWord,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking getGroups.
 */
export interface GetGroupsArgs {
    applicationId?: string;
    clusterId?: string;
    groupIdLists?: string[];
    groupResourceTypeLists?: string[];
    namespaceId?: string;
    orderBy?: string;
    orderType?: number;
    resultOutputFile?: string;
    searchWord?: string;
    status?: string;
}

/**
 * A collection of values returned by getGroups.
 */
export interface GetGroupsResult {
    readonly applicationId?: string;
    readonly clusterId?: string;
    readonly groupIdLists?: string[];
    readonly groupResourceTypeLists?: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly namespaceId?: string;
    readonly orderBy?: string;
    readonly orderType?: number;
    readonly resultOutputFile?: string;
    readonly results: outputs.Tsf.GetGroupsResult[];
    readonly searchWord?: string;
    readonly status?: string;
}
export function getGroupsOutput(args?: GetGroupsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGroupsResult> {
    return pulumi.output(args).apply((a: any) => getGroups(a, opts))
}

/**
 * A collection of arguments for invoking getGroups.
 */
export interface GetGroupsOutputArgs {
    applicationId?: pulumi.Input<string>;
    clusterId?: pulumi.Input<string>;
    groupIdLists?: pulumi.Input<pulumi.Input<string>[]>;
    groupResourceTypeLists?: pulumi.Input<pulumi.Input<string>[]>;
    namespaceId?: pulumi.Input<string>;
    orderBy?: pulumi.Input<string>;
    orderType?: pulumi.Input<number>;
    resultOutputFile?: pulumi.Input<string>;
    searchWord?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
}
