// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dts.Inputs
{

    public sealed class MigrateJobMigrateOptionDatabaseTableDatabaseTableArgs : global::Pulumi.ResourceArgs
    {
        [Input("newTableName")]
        public Input<string>? NewTableName { get; set; }

        [Input("tableEditMode")]
        public Input<string>? TableEditMode { get; set; }

        [Input("tableName")]
        public Input<string>? TableName { get; set; }

        [Input("tmpTables")]
        private InputList<string>? _tmpTables;
        public InputList<string> TmpTables
        {
            get => _tmpTables ?? (_tmpTables = new InputList<string>());
            set => _tmpTables = value;
        }

        public MigrateJobMigrateOptionDatabaseTableDatabaseTableArgs()
        {
        }
        public static new MigrateJobMigrateOptionDatabaseTableDatabaseTableArgs Empty => new MigrateJobMigrateOptionDatabaseTableDatabaseTableArgs();
    }
}
