// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dcdb.Inputs
{

    public sealed class GetUpgradePriceSplitShardConfigInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("shardInstanceIds", required: true)]
        private InputList<string>? _shardInstanceIds;
        public InputList<string> ShardInstanceIds
        {
            get => _shardInstanceIds ?? (_shardInstanceIds = new InputList<string>());
            set => _shardInstanceIds = value;
        }

        [Input("shardMemory", required: true)]
        public Input<int> ShardMemory { get; set; } = null!;

        [Input("shardStorage", required: true)]
        public Input<int> ShardStorage { get; set; } = null!;

        [Input("splitRate", required: true)]
        public Input<int> SplitRate { get; set; } = null!;

        public GetUpgradePriceSplitShardConfigInputArgs()
        {
        }
        public static new GetUpgradePriceSplitShardConfigInputArgs Empty => new GetUpgradePriceSplitShardConfigInputArgs();
    }
}
