// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cynosdb.Outputs
{

    [OutputType]
    public sealed class GetClusterParamLogsClusterParamLogResult
    {
        public readonly string ClusterId;
        public readonly string CreateTime;
        public readonly string CurrentValue;
        public readonly string InstanceId;
        public readonly string ParamName;
        public readonly string Status;
        public readonly string UpdateTime;
        public readonly string UpdateValue;

        [OutputConstructor]
        private GetClusterParamLogsClusterParamLogResult(
            string clusterId,

            string createTime,

            string currentValue,

            string instanceId,

            string paramName,

            string status,

            string updateTime,

            string updateValue)
        {
            ClusterId = clusterId;
            CreateTime = createTime;
            CurrentValue = currentValue;
            InstanceId = instanceId;
            ParamName = paramName;
            Status = status;
            UpdateTime = updateTime;
            UpdateValue = updateValue;
        }
    }
}
