// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tcr
{
    public static class GetRepositories
    {
        public static Task<GetRepositoriesResult> InvokeAsync(GetRepositoriesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRepositoriesResult>("tencentcloud:Tcr/getRepositories:getRepositories", args ?? new GetRepositoriesArgs(), options.WithDefaults());

        public static Output<GetRepositoriesResult> Invoke(GetRepositoriesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRepositoriesResult>("tencentcloud:Tcr/getRepositories:getRepositories", args ?? new GetRepositoriesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRepositoriesArgs : global::Pulumi.InvokeArgs
    {
        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        [Input("namespaceName", required: true)]
        public string NamespaceName { get; set; } = null!;

        [Input("repositoryName")]
        public string? RepositoryName { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetRepositoriesArgs()
        {
        }
        public static new GetRepositoriesArgs Empty => new GetRepositoriesArgs();
    }

    public sealed class GetRepositoriesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("namespaceName", required: true)]
        public Input<string> NamespaceName { get; set; } = null!;

        [Input("repositoryName")]
        public Input<string>? RepositoryName { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetRepositoriesInvokeArgs()
        {
        }
        public static new GetRepositoriesInvokeArgs Empty => new GetRepositoriesInvokeArgs();
    }


    [OutputType]
    public sealed class GetRepositoriesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;
        public readonly string NamespaceName;
        public readonly ImmutableArray<Outputs.GetRepositoriesRepositoryListResult> RepositoryLists;
        public readonly string? RepositoryName;
        public readonly string? ResultOutputFile;

        [OutputConstructor]
        private GetRepositoriesResult(
            string id,

            string instanceId,

            string namespaceName,

            ImmutableArray<Outputs.GetRepositoriesRepositoryListResult> repositoryLists,

            string? repositoryName,

            string? resultOutputFile)
        {
            Id = id;
            InstanceId = instanceId;
            NamespaceName = namespaceName;
            RepositoryLists = repositoryLists;
            RepositoryName = repositoryName;
            ResultOutputFile = resultOutputFile;
        }
    }
}
