// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tdmq.Outputs
{

    [OutputType]
    public sealed class GetPublishersFilterResult
    {
        public readonly string? Name;
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private GetPublishersFilterResult(
            string? name,

            ImmutableArray<string> values)
        {
            Name = name;
            Values = values;
        }
    }
}
