// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Sqlserver.Outputs
{

    [OutputType]
    public sealed class MigrationSource
    {
        public readonly string? CvmId;
        public readonly string? InstanceId;
        public readonly string? Ip;
        public readonly string? Password;
        public readonly int? Port;
        public readonly string? SubnetId;
        public readonly string? UrlPassword;
        public readonly ImmutableArray<string> Urls;
        public readonly string? UserName;
        public readonly string? VpcId;

        [OutputConstructor]
        private MigrationSource(
            string? cvmId,

            string? instanceId,

            string? ip,

            string? password,

            int? port,

            string? subnetId,

            string? urlPassword,

            ImmutableArray<string> urls,

            string? userName,

            string? vpcId)
        {
            CvmId = cvmId;
            InstanceId = instanceId;
            Ip = ip;
            Password = password;
            Port = port;
            SubnetId = subnetId;
            UrlPassword = urlPassword;
            Urls = urls;
            UserName = userName;
            VpcId = vpcId;
        }
    }
}
