// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.As
{
    public static class GetLastActivity
    {
        public static Task<GetLastActivityResult> InvokeAsync(GetLastActivityArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetLastActivityResult>("tencentcloud:As/getLastActivity:getLastActivity", args ?? new GetLastActivityArgs(), options.WithDefaults());

        public static Output<GetLastActivityResult> Invoke(GetLastActivityInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetLastActivityResult>("tencentcloud:As/getLastActivity:getLastActivity", args ?? new GetLastActivityInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetLastActivityArgs : global::Pulumi.InvokeArgs
    {
        [Input("autoScalingGroupIds", required: true)]
        private List<string>? _autoScalingGroupIds;
        public List<string> AutoScalingGroupIds
        {
            get => _autoScalingGroupIds ?? (_autoScalingGroupIds = new List<string>());
            set => _autoScalingGroupIds = value;
        }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetLastActivityArgs()
        {
        }
        public static new GetLastActivityArgs Empty => new GetLastActivityArgs();
    }

    public sealed class GetLastActivityInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("autoScalingGroupIds", required: true)]
        private InputList<string>? _autoScalingGroupIds;
        public InputList<string> AutoScalingGroupIds
        {
            get => _autoScalingGroupIds ?? (_autoScalingGroupIds = new InputList<string>());
            set => _autoScalingGroupIds = value;
        }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetLastActivityInvokeArgs()
        {
        }
        public static new GetLastActivityInvokeArgs Empty => new GetLastActivityInvokeArgs();
    }


    [OutputType]
    public sealed class GetLastActivityResult
    {
        public readonly ImmutableArray<Outputs.GetLastActivityActivitySetResult> ActivitySets;
        public readonly ImmutableArray<string> AutoScalingGroupIds;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? ResultOutputFile;

        [OutputConstructor]
        private GetLastActivityResult(
            ImmutableArray<Outputs.GetLastActivityActivitySetResult> activitySets,

            ImmutableArray<string> autoScalingGroupIds,

            string id,

            string? resultOutputFile)
        {
            ActivitySets = activitySets;
            AutoScalingGroupIds = autoScalingGroupIds;
            Id = id;
            ResultOutputFile = resultOutputFile;
        }
    }
}
