// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cdn.Outputs
{

    [OutputType]
    public sealed class UrlPurgePurgeHistory
    {
        public readonly string? CreateTime;
        public readonly string? FlushType;
        public readonly string? PurgeType;
        public readonly string? Status;
        public readonly string? TaskId;
        public readonly string? Url;

        [OutputConstructor]
        private UrlPurgePurgeHistory(
            string? createTime,

            string? flushType,

            string? purgeType,

            string? status,

            string? taskId,

            string? url)
        {
            CreateTime = createTime;
            FlushType = flushType;
            PurgeType = purgeType;
            Status = status;
            TaskId = taskId;
            Url = url;
        }
    }
}
