// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbbrain

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetTopSpaceSchemas(ctx *pulumi.Context, args *GetTopSpaceSchemasArgs, opts ...pulumi.InvokeOption) (*GetTopSpaceSchemasResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTopSpaceSchemasResult
	err := ctx.Invoke("tencentcloud:Dbbrain/getTopSpaceSchemas:getTopSpaceSchemas", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTopSpaceSchemas.
type GetTopSpaceSchemasArgs struct {
	InstanceId       string  `pulumi:"instanceId"`
	Limit            *int    `pulumi:"limit"`
	Product          *string `pulumi:"product"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	SortBy           *string `pulumi:"sortBy"`
}

// A collection of values returned by getTopSpaceSchemas.
type GetTopSpaceSchemasResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id               string                             `pulumi:"id"`
	InstanceId       string                             `pulumi:"instanceId"`
	Limit            *int                               `pulumi:"limit"`
	Product          *string                            `pulumi:"product"`
	ResultOutputFile *string                            `pulumi:"resultOutputFile"`
	SortBy           *string                            `pulumi:"sortBy"`
	Timestamp        int                                `pulumi:"timestamp"`
	TopSpaceSchemas  []GetTopSpaceSchemasTopSpaceSchema `pulumi:"topSpaceSchemas"`
}

func GetTopSpaceSchemasOutput(ctx *pulumi.Context, args GetTopSpaceSchemasOutputArgs, opts ...pulumi.InvokeOption) GetTopSpaceSchemasResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetTopSpaceSchemasResult, error) {
			args := v.(GetTopSpaceSchemasArgs)
			r, err := GetTopSpaceSchemas(ctx, &args, opts...)
			var s GetTopSpaceSchemasResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetTopSpaceSchemasResultOutput)
}

// A collection of arguments for invoking getTopSpaceSchemas.
type GetTopSpaceSchemasOutputArgs struct {
	InstanceId       pulumi.StringInput    `pulumi:"instanceId"`
	Limit            pulumi.IntPtrInput    `pulumi:"limit"`
	Product          pulumi.StringPtrInput `pulumi:"product"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
	SortBy           pulumi.StringPtrInput `pulumi:"sortBy"`
}

func (GetTopSpaceSchemasOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTopSpaceSchemasArgs)(nil)).Elem()
}

// A collection of values returned by getTopSpaceSchemas.
type GetTopSpaceSchemasResultOutput struct{ *pulumi.OutputState }

func (GetTopSpaceSchemasResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTopSpaceSchemasResult)(nil)).Elem()
}

func (o GetTopSpaceSchemasResultOutput) ToGetTopSpaceSchemasResultOutput() GetTopSpaceSchemasResultOutput {
	return o
}

func (o GetTopSpaceSchemasResultOutput) ToGetTopSpaceSchemasResultOutputWithContext(ctx context.Context) GetTopSpaceSchemasResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetTopSpaceSchemasResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTopSpaceSchemasResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTopSpaceSchemasResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetTopSpaceSchemasResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetTopSpaceSchemasResultOutput) Limit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetTopSpaceSchemasResult) *int { return v.Limit }).(pulumi.IntPtrOutput)
}

func (o GetTopSpaceSchemasResultOutput) Product() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTopSpaceSchemasResult) *string { return v.Product }).(pulumi.StringPtrOutput)
}

func (o GetTopSpaceSchemasResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTopSpaceSchemasResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetTopSpaceSchemasResultOutput) SortBy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTopSpaceSchemasResult) *string { return v.SortBy }).(pulumi.StringPtrOutput)
}

func (o GetTopSpaceSchemasResultOutput) Timestamp() pulumi.IntOutput {
	return o.ApplyT(func(v GetTopSpaceSchemasResult) int { return v.Timestamp }).(pulumi.IntOutput)
}

func (o GetTopSpaceSchemasResultOutput) TopSpaceSchemas() GetTopSpaceSchemasTopSpaceSchemaArrayOutput {
	return o.ApplyT(func(v GetTopSpaceSchemasResult) []GetTopSpaceSchemasTopSpaceSchema { return v.TopSpaceSchemas }).(GetTopSpaceSchemasTopSpaceSchemaArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTopSpaceSchemasResultOutput{})
}
