// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cynosdb
{
    public static class GetAuditLogs
    {
        public static Task<GetAuditLogsResult> InvokeAsync(GetAuditLogsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAuditLogsResult>("tencentcloud:Cynosdb/getAuditLogs:getAuditLogs", args ?? new GetAuditLogsArgs(), options.WithDefaults());

        public static Output<GetAuditLogsResult> Invoke(GetAuditLogsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAuditLogsResult>("tencentcloud:Cynosdb/getAuditLogs:getAuditLogs", args ?? new GetAuditLogsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAuditLogsArgs : global::Pulumi.InvokeArgs
    {
        [Input("endTime", required: true)]
        public string EndTime { get; set; } = null!;

        [Input("filter")]
        public Inputs.GetAuditLogsFilterArgs? Filter { get; set; }

        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        [Input("order")]
        public string? Order { get; set; }

        [Input("orderBy")]
        public string? OrderBy { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        [Input("startTime", required: true)]
        public string StartTime { get; set; } = null!;

        public GetAuditLogsArgs()
        {
        }
        public static new GetAuditLogsArgs Empty => new GetAuditLogsArgs();
    }

    public sealed class GetAuditLogsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("endTime", required: true)]
        public Input<string> EndTime { get; set; } = null!;

        [Input("filter")]
        public Input<Inputs.GetAuditLogsFilterInputArgs>? Filter { get; set; }

        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("order")]
        public Input<string>? Order { get; set; }

        [Input("orderBy")]
        public Input<string>? OrderBy { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        [Input("startTime", required: true)]
        public Input<string> StartTime { get; set; } = null!;

        public GetAuditLogsInvokeArgs()
        {
        }
        public static new GetAuditLogsInvokeArgs Empty => new GetAuditLogsInvokeArgs();
    }


    [OutputType]
    public sealed class GetAuditLogsResult
    {
        public readonly string EndTime;
        public readonly Outputs.GetAuditLogsFilterResult? Filter;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;
        public readonly ImmutableArray<Outputs.GetAuditLogsItemResult> Items;
        public readonly string? Order;
        public readonly string? OrderBy;
        public readonly string? ResultOutputFile;
        public readonly string StartTime;

        [OutputConstructor]
        private GetAuditLogsResult(
            string endTime,

            Outputs.GetAuditLogsFilterResult? filter,

            string id,

            string instanceId,

            ImmutableArray<Outputs.GetAuditLogsItemResult> items,

            string? order,

            string? orderBy,

            string? resultOutputFile,

            string startTime)
        {
            EndTime = endTime;
            Filter = filter;
            Id = id;
            InstanceId = instanceId;
            Items = items;
            Order = order;
            OrderBy = orderBy;
            ResultOutputFile = resultOutputFile;
            StartTime = startTime;
        }
    }
}
