// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Lighthouse.Outputs
{

    [OutputType]
    public sealed class GetModifyInstanceBundleModifyBundleSetBundleResult
    {
        public readonly string BundleDisplayLabel;
        public readonly string BundleId;
        public readonly string BundleSalesState;
        public readonly string BundleType;
        public readonly string BundleTypeDescription;
        public readonly int Cpu;
        public readonly string InternetChargeType;
        public readonly int InternetMaxBandwidthOut;
        public readonly int Memory;
        public readonly int MonthlyTraffic;
        public readonly ImmutableArray<Outputs.GetModifyInstanceBundleModifyBundleSetBundlePriceResult> Prices;
        public readonly bool SupportLinuxUnixPlatform;
        public readonly bool SupportWindowsPlatform;
        public readonly int SystemDiskSize;
        public readonly string SystemDiskType;

        [OutputConstructor]
        private GetModifyInstanceBundleModifyBundleSetBundleResult(
            string bundleDisplayLabel,

            string bundleId,

            string bundleSalesState,

            string bundleType,

            string bundleTypeDescription,

            int cpu,

            string internetChargeType,

            int internetMaxBandwidthOut,

            int memory,

            int monthlyTraffic,

            ImmutableArray<Outputs.GetModifyInstanceBundleModifyBundleSetBundlePriceResult> prices,

            bool supportLinuxUnixPlatform,

            bool supportWindowsPlatform,

            int systemDiskSize,

            string systemDiskType)
        {
            BundleDisplayLabel = bundleDisplayLabel;
            BundleId = bundleId;
            BundleSalesState = bundleSalesState;
            BundleType = bundleType;
            BundleTypeDescription = bundleTypeDescription;
            Cpu = cpu;
            InternetChargeType = internetChargeType;
            InternetMaxBandwidthOut = internetMaxBandwidthOut;
            Memory = memory;
            MonthlyTraffic = monthlyTraffic;
            Prices = prices;
            SupportLinuxUnixPlatform = supportLinuxUnixPlatform;
            SupportWindowsPlatform = supportWindowsPlatform;
            SystemDiskSize = systemDiskSize;
            SystemDiskType = systemDiskType;
        }
    }
}
