// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Lighthouse.Outputs
{

    [OutputType]
    public sealed class GetResetInstanceBlueprintResetInstanceBlueprintSetBlueprintInfoResult
    {
        public readonly string BlueprintId;
        public readonly string BlueprintName;
        public readonly string BlueprintState;
        public readonly string BlueprintType;
        public readonly string CommunityUrl;
        public readonly string CreatedTime;
        public readonly string Description;
        public readonly string DisplayTitle;
        public readonly string DisplayVersion;
        public readonly string DockerVersion;
        public readonly string GuideUrl;
        public readonly string ImageId;
        public readonly string ImageUrl;
        public readonly string OsName;
        public readonly string Platform;
        public readonly string PlatformType;
        public readonly int RequiredMemorySize;
        public readonly int RequiredSystemDiskSize;
        public readonly ImmutableArray<string> SceneIdSets;
        public readonly bool SupportAutomationTools;

        [OutputConstructor]
        private GetResetInstanceBlueprintResetInstanceBlueprintSetBlueprintInfoResult(
            string blueprintId,

            string blueprintName,

            string blueprintState,

            string blueprintType,

            string communityUrl,

            string createdTime,

            string description,

            string displayTitle,

            string displayVersion,

            string dockerVersion,

            string guideUrl,

            string imageId,

            string imageUrl,

            string osName,

            string platform,

            string platformType,

            int requiredMemorySize,

            int requiredSystemDiskSize,

            ImmutableArray<string> sceneIdSets,

            bool supportAutomationTools)
        {
            BlueprintId = blueprintId;
            BlueprintName = blueprintName;
            BlueprintState = blueprintState;
            BlueprintType = blueprintType;
            CommunityUrl = communityUrl;
            CreatedTime = createdTime;
            Description = description;
            DisplayTitle = displayTitle;
            DisplayVersion = displayVersion;
            DockerVersion = dockerVersion;
            GuideUrl = guideUrl;
            ImageId = imageId;
            ImageUrl = imageUrl;
            OsName = osName;
            Platform = platform;
            PlatformType = platformType;
            RequiredMemorySize = requiredMemorySize;
            RequiredSystemDiskSize = requiredSystemDiskSize;
            SceneIdSets = sceneIdSets;
            SupportAutomationTools = supportAutomationTools;
        }
    }
}
