// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Lighthouse.Outputs
{

    [OutputType]
    public sealed class RenewDiskRenewDiskChargePrepaid
    {
        public readonly string? CurInstanceDeadline;
        public readonly int? Period;
        public readonly string? RenewFlag;
        public readonly string? TimeUnit;

        [OutputConstructor]
        private RenewDiskRenewDiskChargePrepaid(
            string? curInstanceDeadline,

            int? period,

            string? renewFlag,

            string? timeUnit)
        {
            CurInstanceDeadline = curInstanceDeadline;
            Period = period;
            RenewFlag = renewFlag;
            TimeUnit = timeUnit;
        }
    }
}
