// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cls.Inputs
{

    public sealed class CkafkaConsumerCkafkaArgs : global::Pulumi.ResourceArgs
    {
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("instanceName", required: true)]
        public Input<string> InstanceName { get; set; } = null!;

        [Input("topicId", required: true)]
        public Input<string> TopicId { get; set; } = null!;

        [Input("topicName", required: true)]
        public Input<string> TopicName { get; set; } = null!;

        [Input("vip", required: true)]
        public Input<string> Vip { get; set; } = null!;

        [Input("vport", required: true)]
        public Input<string> Vport { get; set; } = null!;

        public CkafkaConsumerCkafkaArgs()
        {
        }
        public static new CkafkaConsumerCkafkaArgs Empty => new CkafkaConsumerCkafkaArgs();
    }
}
