// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tcr

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetVpcAttachments(ctx *pulumi.Context, args *GetVpcAttachmentsArgs, opts ...pulumi.InvokeOption) (*GetVpcAttachmentsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVpcAttachmentsResult
	err := ctx.Invoke("tencentcloud:Tcr/getVpcAttachments:getVpcAttachments", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVpcAttachments.
type GetVpcAttachmentsArgs struct {
	InstanceId       string  `pulumi:"instanceId"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	SubnetId         *string `pulumi:"subnetId"`
	VpcId            *string `pulumi:"vpcId"`
}

// A collection of values returned by getVpcAttachments.
type GetVpcAttachmentsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                 string                               `pulumi:"id"`
	InstanceId         string                               `pulumi:"instanceId"`
	ResultOutputFile   *string                              `pulumi:"resultOutputFile"`
	SubnetId           *string                              `pulumi:"subnetId"`
	VpcAttachmentLists []GetVpcAttachmentsVpcAttachmentList `pulumi:"vpcAttachmentLists"`
	VpcId              *string                              `pulumi:"vpcId"`
}

func GetVpcAttachmentsOutput(ctx *pulumi.Context, args GetVpcAttachmentsOutputArgs, opts ...pulumi.InvokeOption) GetVpcAttachmentsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVpcAttachmentsResult, error) {
			args := v.(GetVpcAttachmentsArgs)
			r, err := GetVpcAttachments(ctx, &args, opts...)
			var s GetVpcAttachmentsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetVpcAttachmentsResultOutput)
}

// A collection of arguments for invoking getVpcAttachments.
type GetVpcAttachmentsOutputArgs struct {
	InstanceId       pulumi.StringInput    `pulumi:"instanceId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
	SubnetId         pulumi.StringPtrInput `pulumi:"subnetId"`
	VpcId            pulumi.StringPtrInput `pulumi:"vpcId"`
}

func (GetVpcAttachmentsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpcAttachmentsArgs)(nil)).Elem()
}

// A collection of values returned by getVpcAttachments.
type GetVpcAttachmentsResultOutput struct{ *pulumi.OutputState }

func (GetVpcAttachmentsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpcAttachmentsResult)(nil)).Elem()
}

func (o GetVpcAttachmentsResultOutput) ToGetVpcAttachmentsResultOutput() GetVpcAttachmentsResultOutput {
	return o
}

func (o GetVpcAttachmentsResultOutput) ToGetVpcAttachmentsResultOutputWithContext(ctx context.Context) GetVpcAttachmentsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetVpcAttachmentsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcAttachmentsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVpcAttachmentsResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcAttachmentsResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetVpcAttachmentsResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVpcAttachmentsResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetVpcAttachmentsResultOutput) SubnetId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVpcAttachmentsResult) *string { return v.SubnetId }).(pulumi.StringPtrOutput)
}

func (o GetVpcAttachmentsResultOutput) VpcAttachmentLists() GetVpcAttachmentsVpcAttachmentListArrayOutput {
	return o.ApplyT(func(v GetVpcAttachmentsResult) []GetVpcAttachmentsVpcAttachmentList { return v.VpcAttachmentLists }).(GetVpcAttachmentsVpcAttachmentListArrayOutput)
}

func (o GetVpcAttachmentsResultOutput) VpcId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVpcAttachmentsResult) *string { return v.VpcId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVpcAttachmentsResultOutput{})
}
