// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Vod.Outputs
{

    [OutputType]
    public sealed class GetProcedureTemplatesTemplateListMediaProcessTaskCoverBySnapshotTaskListResult
    {
        public readonly string Definition;
        public readonly string PositionType;
        public readonly double PositionValue;
        public readonly ImmutableArray<Outputs.GetProcedureTemplatesTemplateListMediaProcessTaskCoverBySnapshotTaskListWatermarkListResult> WatermarkLists;

        [OutputConstructor]
        private GetProcedureTemplatesTemplateListMediaProcessTaskCoverBySnapshotTaskListResult(
            string definition,

            string positionType,

            double positionValue,

            ImmutableArray<Outputs.GetProcedureTemplatesTemplateListMediaProcessTaskCoverBySnapshotTaskListWatermarkListResult> watermarkLists)
        {
            Definition = definition;
            PositionType = positionType;
            PositionValue = positionValue;
            WatermarkLists = watermarkLists;
        }
    }
}
