// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tem.Outputs
{

    [OutputType]
    public sealed class GatewayIngressRuleHttpPath
    {
        public readonly Outputs.GatewayIngressRuleHttpPathBackend Backend;
        public readonly string Path;

        [OutputConstructor]
        private GatewayIngressRuleHttpPath(
            Outputs.GatewayIngressRuleHttpPathBackend backend,

            string path)
        {
            Backend = backend;
            Path = path;
        }
    }
}
