// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tem.Outputs
{

    [OutputType]
    public sealed class ScaleRuleAutoscalerCronHorizontalAutoscaler
    {
        public readonly bool Enabled;
        public readonly string Name;
        public readonly string Period;
        public readonly int Priority;
        public readonly ImmutableArray<Outputs.ScaleRuleAutoscalerCronHorizontalAutoscalerSchedule> Schedules;

        [OutputConstructor]
        private ScaleRuleAutoscalerCronHorizontalAutoscaler(
            bool enabled,

            string name,

            string period,

            int priority,

            ImmutableArray<Outputs.ScaleRuleAutoscalerCronHorizontalAutoscalerSchedule> schedules)
        {
            Enabled = enabled;
            Name = name;
            Period = period;
            Priority = priority;
            Schedules = schedules;
        }
    }
}
