// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getParameters(args: GetParametersArgs, opts?: pulumi.InvokeOptions): Promise<GetParametersResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Dcdb/getParameters:getParameters", {
        "instanceId": args.instanceId,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getParameters.
 */
export interface GetParametersArgs {
    instanceId: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getParameters.
 */
export interface GetParametersResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceId: string;
    readonly lists: outputs.Dcdb.GetParametersList[];
    readonly resultOutputFile?: string;
}
export function getParametersOutput(args: GetParametersOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetParametersResult> {
    return pulumi.output(args).apply((a: any) => getParameters(a, opts))
}

/**
 * A collection of arguments for invoking getParameters.
 */
export interface GetParametersOutputArgs {
    instanceId: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
