// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cvm.Outputs
{

    [OutputType]
    public sealed class GetChcDeniedActionsChcHostDeniedActionSetResult
    {
        public readonly string ChcId;
        public readonly ImmutableArray<string> DenyActions;
        public readonly string State;

        [OutputConstructor]
        private GetChcDeniedActionsChcHostDeniedActionSetResult(
            string chcId,

            ImmutableArray<string> denyActions,

            string state)
        {
            ChcId = chcId;
            DenyActions = denyActions;
            State = state;
        }
    }
}
