// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Postgresql.Outputs
{

    [OutputType]
    public sealed class GetReadonlyGroupsReadOnlyGroupListReadOnlyDbInstanceListDbInstanceNetInfoResult
    {
        public readonly string Address;
        public readonly string Ip;
        public readonly string NetType;
        public readonly int Port;
        public readonly string ProtocolType;
        public readonly string Status;
        public readonly string SubnetId;
        public readonly string VpcId;

        [OutputConstructor]
        private GetReadonlyGroupsReadOnlyGroupListReadOnlyDbInstanceListDbInstanceNetInfoResult(
            string address,

            string ip,

            string netType,

            int port,

            string protocolType,

            string status,

            string subnetId,

            string vpcId)
        {
            Address = address;
            Ip = ip;
            NetType = netType;
            Port = port;
            ProtocolType = protocolType;
            Status = status;
            SubnetId = subnetId;
            VpcId = vpcId;
        }
    }
}
