// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Ssm
{
    public static class GetSecrets
    {
        public static Task<GetSecretsResult> InvokeAsync(GetSecretsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSecretsResult>("tencentcloud:Ssm/getSecrets:getSecrets", args ?? new GetSecretsArgs(), options.WithDefaults());

        public static Output<GetSecretsResult> Invoke(GetSecretsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecretsResult>("tencentcloud:Ssm/getSecrets:getSecrets", args ?? new GetSecretsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSecretsArgs : global::Pulumi.InvokeArgs
    {
        [Input("orderType")]
        public int? OrderType { get; set; }

        [Input("productName")]
        public string? ProductName { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        [Input("secretName")]
        public string? SecretName { get; set; }

        [Input("secretType")]
        public int? SecretType { get; set; }

        [Input("state")]
        public int? State { get; set; }

        [Input("tags")]
        private Dictionary<string, object>? _tags;
        public Dictionary<string, object> Tags
        {
            get => _tags ?? (_tags = new Dictionary<string, object>());
            set => _tags = value;
        }

        public GetSecretsArgs()
        {
        }
        public static new GetSecretsArgs Empty => new GetSecretsArgs();
    }

    public sealed class GetSecretsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("orderType")]
        public Input<int>? OrderType { get; set; }

        [Input("productName")]
        public Input<string>? ProductName { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        [Input("secretName")]
        public Input<string>? SecretName { get; set; }

        [Input("secretType")]
        public Input<int>? SecretType { get; set; }

        [Input("state")]
        public Input<int>? State { get; set; }

        [Input("tags")]
        private InputMap<object>? _tags;
        public InputMap<object> Tags
        {
            get => _tags ?? (_tags = new InputMap<object>());
            set => _tags = value;
        }

        public GetSecretsInvokeArgs()
        {
        }
        public static new GetSecretsInvokeArgs Empty => new GetSecretsInvokeArgs();
    }


    [OutputType]
    public sealed class GetSecretsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int? OrderType;
        public readonly string? ProductName;
        public readonly string? ResultOutputFile;
        public readonly ImmutableArray<Outputs.GetSecretsSecretListResult> SecretLists;
        public readonly string? SecretName;
        public readonly int? SecretType;
        public readonly int? State;
        public readonly ImmutableDictionary<string, object>? Tags;

        [OutputConstructor]
        private GetSecretsResult(
            string id,

            int? orderType,

            string? productName,

            string? resultOutputFile,

            ImmutableArray<Outputs.GetSecretsSecretListResult> secretLists,

            string? secretName,

            int? secretType,

            int? state,

            ImmutableDictionary<string, object>? tags)
        {
            Id = id;
            OrderType = orderType;
            ProductName = productName;
            ResultOutputFile = resultOutputFile;
            SecretLists = secretLists;
            SecretName = secretName;
            SecretType = secretType;
            State = state;
            Tags = tags;
        }
    }
}
