// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tcm.Outputs
{

    [OutputType]
    public sealed class MeshConfig
    {
        public readonly Outputs.MeshConfigInject? Inject;
        public readonly Outputs.MeshConfigIstio? Istio;
        public readonly Outputs.MeshConfigPrometheus? Prometheus;
        public readonly Outputs.MeshConfigSidecarResources? SidecarResources;
        public readonly Outputs.MeshConfigTracing? Tracing;

        [OutputConstructor]
        private MeshConfig(
            Outputs.MeshConfigInject? inject,

            Outputs.MeshConfigIstio? istio,

            Outputs.MeshConfigPrometheus? prometheus,

            Outputs.MeshConfigSidecarResources? sidecarResources,

            Outputs.MeshConfigTracing? tracing)
        {
            Inject = inject;
            Istio = istio;
            Prometheus = prometheus;
            SidecarResources = sidecarResources;
            Tracing = tracing;
        }
    }
}
