// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Clb.Outputs
{

    [OutputType]
    public sealed class GetInstanceByCertIdCertSetLoadBalancerExtraInfoResult
    {
        public readonly string TgwGroupName;
        public readonly bool ZhiTong;

        [OutputConstructor]
        private GetInstanceByCertIdCertSetLoadBalancerExtraInfoResult(
            string tgwGroupName,

            bool zhiTong)
        {
            TgwGroupName = tgwGroupName;
            ZhiTong = zhiTong;
        }
    }
}
