// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dts.Outputs
{

    [OutputType]
    public sealed class GetMigrateJobsListDstInfoResult
    {
        public readonly string AccessType;
        public readonly string DatabaseType;
        public readonly ImmutableArray<Outputs.GetMigrateJobsListDstInfoInfoResult> Infos;
        public readonly string NodeType;
        public readonly string Region;

        [OutputConstructor]
        private GetMigrateJobsListDstInfoResult(
            string accessType,

            string databaseType,

            ImmutableArray<Outputs.GetMigrateJobsListDstInfoInfoResult> infos,

            string nodeType,

            string region)
        {
            AccessType = accessType;
            DatabaseType = databaseType;
            Infos = infos;
            NodeType = nodeType;
            Region = region;
        }
    }
}
