// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dts.Outputs
{

    [OutputType]
    public sealed class GetSyncJobsListOptionResult
    {
        public readonly bool AddAdditionalColumn;
        public readonly ImmutableArray<Outputs.GetSyncJobsListOptionConflictHandleOptionResult> ConflictHandleOptions;
        public readonly string ConflictHandleType;
        public readonly ImmutableArray<Outputs.GetSyncJobsListOptionDdlOptionResult> DdlOptions;
        public readonly string DealOfExistSameTable;
        public readonly string InitType;
        public readonly ImmutableArray<string> OpTypes;

        [OutputConstructor]
        private GetSyncJobsListOptionResult(
            bool addAdditionalColumn,

            ImmutableArray<Outputs.GetSyncJobsListOptionConflictHandleOptionResult> conflictHandleOptions,

            string conflictHandleType,

            ImmutableArray<Outputs.GetSyncJobsListOptionDdlOptionResult> ddlOptions,

            string dealOfExistSameTable,

            string initType,

            ImmutableArray<string> opTypes)
        {
            AddAdditionalColumn = addAdditionalColumn;
            ConflictHandleOptions = conflictHandleOptions;
            ConflictHandleType = conflictHandleType;
            DdlOptions = ddlOptions;
            DealOfExistSameTable = dealOfExistSameTable;
            InitType = initType;
            OpTypes = opTypes;
        }
    }
}
