// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Vpc.Outputs
{

    [OutputType]
    public sealed class GetSecurityGroupLimitsSecurityGroupLimitSetResult
    {
        public readonly int InstanceSecurityGroupLimit;
        public readonly int ReferredSecurityGroupLimit;
        public readonly int SecurityGroupExtendedPolicyLimit;
        public readonly int SecurityGroupInstanceLimit;
        public readonly int SecurityGroupLimit;
        public readonly int SecurityGroupPolicyLimit;
        public readonly int SecurityGroupReferredCvmAndEniLimit;
        public readonly int SecurityGroupReferredSvcLimit;

        [OutputConstructor]
        private GetSecurityGroupLimitsSecurityGroupLimitSetResult(
            int instanceSecurityGroupLimit,

            int referredSecurityGroupLimit,

            int securityGroupExtendedPolicyLimit,

            int securityGroupInstanceLimit,

            int securityGroupLimit,

            int securityGroupPolicyLimit,

            int securityGroupReferredCvmAndEniLimit,

            int securityGroupReferredSvcLimit)
        {
            InstanceSecurityGroupLimit = instanceSecurityGroupLimit;
            ReferredSecurityGroupLimit = referredSecurityGroupLimit;
            SecurityGroupExtendedPolicyLimit = securityGroupExtendedPolicyLimit;
            SecurityGroupInstanceLimit = securityGroupInstanceLimit;
            SecurityGroupLimit = securityGroupLimit;
            SecurityGroupPolicyLimit = securityGroupPolicyLimit;
            SecurityGroupReferredCvmAndEniLimit = securityGroupReferredCvmAndEniLimit;
            SecurityGroupReferredSvcLimit = securityGroupReferredSvcLimit;
        }
    }
}
