// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getGatewayInstances(args?: GetGatewayInstancesArgs, opts?: pulumi.InvokeOptions): Promise<GetGatewayInstancesResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Dc/getGatewayInstances:getGatewayInstances", {
        "dcgId": args.dcgId,
        "name": args.name,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getGatewayInstances.
 */
export interface GetGatewayInstancesArgs {
    dcgId?: string;
    name?: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getGatewayInstances.
 */
export interface GetGatewayInstancesResult {
    readonly dcgId?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceLists: outputs.Dc.GetGatewayInstancesInstanceList[];
    readonly name?: string;
    readonly resultOutputFile?: string;
}
export function getGatewayInstancesOutput(args?: GetGatewayInstancesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGatewayInstancesResult> {
    return pulumi.output(args).apply((a: any) => getGatewayInstances(a, opts))
}

/**
 * A collection of arguments for invoking getGatewayInstances.
 */
export interface GetGatewayInstancesOutputArgs {
    dcgId?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
