// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Monitor.Inputs
{

    public sealed class TmpTkeGlobalNotificationNotificationAlertManagerGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        [Input("clusterType")]
        public Input<string>? ClusterType { get; set; }

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public TmpTkeGlobalNotificationNotificationAlertManagerGetArgs()
        {
        }
        public static new TmpTkeGlobalNotificationNotificationAlertManagerGetArgs Empty => new TmpTkeGlobalNotificationNotificationAlertManagerGetArgs();
    }
}
