// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Gaap
{
    public static class GetHttpRules
    {
        public static Task<GetHttpRulesResult> InvokeAsync(GetHttpRulesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetHttpRulesResult>("tencentcloud:Gaap/getHttpRules:getHttpRules", args ?? new GetHttpRulesArgs(), options.WithDefaults());

        public static Output<GetHttpRulesResult> Invoke(GetHttpRulesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetHttpRulesResult>("tencentcloud:Gaap/getHttpRules:getHttpRules", args ?? new GetHttpRulesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetHttpRulesArgs : global::Pulumi.InvokeArgs
    {
        [Input("domain")]
        public string? Domain { get; set; }

        [Input("forwardHost")]
        public string? ForwardHost { get; set; }

        [Input("listenerId", required: true)]
        public string ListenerId { get; set; } = null!;

        [Input("path")]
        public string? Path { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetHttpRulesArgs()
        {
        }
        public static new GetHttpRulesArgs Empty => new GetHttpRulesArgs();
    }

    public sealed class GetHttpRulesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("forwardHost")]
        public Input<string>? ForwardHost { get; set; }

        [Input("listenerId", required: true)]
        public Input<string> ListenerId { get; set; } = null!;

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetHttpRulesInvokeArgs()
        {
        }
        public static new GetHttpRulesInvokeArgs Empty => new GetHttpRulesInvokeArgs();
    }


    [OutputType]
    public sealed class GetHttpRulesResult
    {
        public readonly string? Domain;
        public readonly string? ForwardHost;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string ListenerId;
        public readonly string? Path;
        public readonly string? ResultOutputFile;
        public readonly ImmutableArray<Outputs.GetHttpRulesRuleResult> Rules;

        [OutputConstructor]
        private GetHttpRulesResult(
            string? domain,

            string? forwardHost,

            string id,

            string listenerId,

            string? path,

            string? resultOutputFile,

            ImmutableArray<Outputs.GetHttpRulesRuleResult> rules)
        {
            Domain = domain;
            ForwardHost = forwardHost;
            Id = id;
            ListenerId = listenerId;
            Path = path;
            ResultOutputFile = resultOutputFile;
            Rules = rules;
        }
    }
}
