// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cynosdb

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetProxyVersion(ctx *pulumi.Context, args *GetProxyVersionArgs, opts ...pulumi.InvokeOption) (*GetProxyVersionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetProxyVersionResult
	err := ctx.Invoke("tencentcloud:Cynosdb/getProxyVersion:getProxyVersion", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProxyVersion.
type GetProxyVersionArgs struct {
	ClusterId        string  `pulumi:"clusterId"`
	ProxyGroupId     *string `pulumi:"proxyGroupId"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getProxyVersion.
type GetProxyVersionResult struct {
	ClusterId           string `pulumi:"clusterId"`
	CurrentProxyVersion string `pulumi:"currentProxyVersion"`
	// The provider-assigned unique ID for this managed resource.
	Id                   string   `pulumi:"id"`
	ProxyGroupId         *string  `pulumi:"proxyGroupId"`
	ResultOutputFile     *string  `pulumi:"resultOutputFile"`
	SupportProxyVersions []string `pulumi:"supportProxyVersions"`
}

func GetProxyVersionOutput(ctx *pulumi.Context, args GetProxyVersionOutputArgs, opts ...pulumi.InvokeOption) GetProxyVersionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetProxyVersionResult, error) {
			args := v.(GetProxyVersionArgs)
			r, err := GetProxyVersion(ctx, &args, opts...)
			var s GetProxyVersionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetProxyVersionResultOutput)
}

// A collection of arguments for invoking getProxyVersion.
type GetProxyVersionOutputArgs struct {
	ClusterId        pulumi.StringInput    `pulumi:"clusterId"`
	ProxyGroupId     pulumi.StringPtrInput `pulumi:"proxyGroupId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetProxyVersionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProxyVersionArgs)(nil)).Elem()
}

// A collection of values returned by getProxyVersion.
type GetProxyVersionResultOutput struct{ *pulumi.OutputState }

func (GetProxyVersionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProxyVersionResult)(nil)).Elem()
}

func (o GetProxyVersionResultOutput) ToGetProxyVersionResultOutput() GetProxyVersionResultOutput {
	return o
}

func (o GetProxyVersionResultOutput) ToGetProxyVersionResultOutputWithContext(ctx context.Context) GetProxyVersionResultOutput {
	return o
}

func (o GetProxyVersionResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetProxyVersionResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

func (o GetProxyVersionResultOutput) CurrentProxyVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetProxyVersionResult) string { return v.CurrentProxyVersion }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetProxyVersionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetProxyVersionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetProxyVersionResultOutput) ProxyGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetProxyVersionResult) *string { return v.ProxyGroupId }).(pulumi.StringPtrOutput)
}

func (o GetProxyVersionResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetProxyVersionResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetProxyVersionResultOutput) SupportProxyVersions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetProxyVersionResult) []string { return v.SupportProxyVersions }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetProxyVersionResultOutput{})
}
