// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Teo.Outputs
{

    [OutputType]
    public sealed class ZoneSettingCompression
    {
        public readonly ImmutableArray<string> Algorithms;
        public readonly string Switch;

        [OutputConstructor]
        private ZoneSettingCompression(
            ImmutableArray<string> algorithms,

            string @switch)
        {
            Algorithms = algorithms;
            Switch = @switch;
        }
    }
}
