// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vod

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAdaptiveDynamicStreamingTemplates(ctx *pulumi.Context, args *GetAdaptiveDynamicStreamingTemplatesArgs, opts ...pulumi.InvokeOption) (*GetAdaptiveDynamicStreamingTemplatesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAdaptiveDynamicStreamingTemplatesResult
	err := ctx.Invoke("tencentcloud:Vod/getAdaptiveDynamicStreamingTemplates:getAdaptiveDynamicStreamingTemplates", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAdaptiveDynamicStreamingTemplates.
type GetAdaptiveDynamicStreamingTemplatesArgs struct {
	Definition       *string `pulumi:"definition"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	SubAppId         *int    `pulumi:"subAppId"`
	Type             *string `pulumi:"type"`
}

// A collection of values returned by getAdaptiveDynamicStreamingTemplates.
type GetAdaptiveDynamicStreamingTemplatesResult struct {
	Definition *string `pulumi:"definition"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                                             `pulumi:"id"`
	ResultOutputFile *string                                            `pulumi:"resultOutputFile"`
	SubAppId         *int                                               `pulumi:"subAppId"`
	TemplateLists    []GetAdaptiveDynamicStreamingTemplatesTemplateList `pulumi:"templateLists"`
	Type             *string                                            `pulumi:"type"`
}

func GetAdaptiveDynamicStreamingTemplatesOutput(ctx *pulumi.Context, args GetAdaptiveDynamicStreamingTemplatesOutputArgs, opts ...pulumi.InvokeOption) GetAdaptiveDynamicStreamingTemplatesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetAdaptiveDynamicStreamingTemplatesResult, error) {
			args := v.(GetAdaptiveDynamicStreamingTemplatesArgs)
			r, err := GetAdaptiveDynamicStreamingTemplates(ctx, &args, opts...)
			var s GetAdaptiveDynamicStreamingTemplatesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetAdaptiveDynamicStreamingTemplatesResultOutput)
}

// A collection of arguments for invoking getAdaptiveDynamicStreamingTemplates.
type GetAdaptiveDynamicStreamingTemplatesOutputArgs struct {
	Definition       pulumi.StringPtrInput `pulumi:"definition"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
	SubAppId         pulumi.IntPtrInput    `pulumi:"subAppId"`
	Type             pulumi.StringPtrInput `pulumi:"type"`
}

func (GetAdaptiveDynamicStreamingTemplatesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAdaptiveDynamicStreamingTemplatesArgs)(nil)).Elem()
}

// A collection of values returned by getAdaptiveDynamicStreamingTemplates.
type GetAdaptiveDynamicStreamingTemplatesResultOutput struct{ *pulumi.OutputState }

func (GetAdaptiveDynamicStreamingTemplatesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAdaptiveDynamicStreamingTemplatesResult)(nil)).Elem()
}

func (o GetAdaptiveDynamicStreamingTemplatesResultOutput) ToGetAdaptiveDynamicStreamingTemplatesResultOutput() GetAdaptiveDynamicStreamingTemplatesResultOutput {
	return o
}

func (o GetAdaptiveDynamicStreamingTemplatesResultOutput) ToGetAdaptiveDynamicStreamingTemplatesResultOutputWithContext(ctx context.Context) GetAdaptiveDynamicStreamingTemplatesResultOutput {
	return o
}

func (o GetAdaptiveDynamicStreamingTemplatesResultOutput) Definition() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAdaptiveDynamicStreamingTemplatesResult) *string { return v.Definition }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAdaptiveDynamicStreamingTemplatesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAdaptiveDynamicStreamingTemplatesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAdaptiveDynamicStreamingTemplatesResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAdaptiveDynamicStreamingTemplatesResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetAdaptiveDynamicStreamingTemplatesResultOutput) SubAppId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetAdaptiveDynamicStreamingTemplatesResult) *int { return v.SubAppId }).(pulumi.IntPtrOutput)
}

func (o GetAdaptiveDynamicStreamingTemplatesResultOutput) TemplateLists() GetAdaptiveDynamicStreamingTemplatesTemplateListArrayOutput {
	return o.ApplyT(func(v GetAdaptiveDynamicStreamingTemplatesResult) []GetAdaptiveDynamicStreamingTemplatesTemplateList {
		return v.TemplateLists
	}).(GetAdaptiveDynamicStreamingTemplatesTemplateListArrayOutput)
}

func (o GetAdaptiveDynamicStreamingTemplatesResultOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAdaptiveDynamicStreamingTemplatesResult) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAdaptiveDynamicStreamingTemplatesResultOutput{})
}
