// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Clb
{
    public static class GetListenerRules
    {
        public static Task<GetListenerRulesResult> InvokeAsync(GetListenerRulesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetListenerRulesResult>("tencentcloud:Clb/getListenerRules:getListenerRules", args ?? new GetListenerRulesArgs(), options.WithDefaults());

        public static Output<GetListenerRulesResult> Invoke(GetListenerRulesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetListenerRulesResult>("tencentcloud:Clb/getListenerRules:getListenerRules", args ?? new GetListenerRulesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetListenerRulesArgs : global::Pulumi.InvokeArgs
    {
        [Input("clbId", required: true)]
        public string ClbId { get; set; } = null!;

        [Input("domain")]
        public string? Domain { get; set; }

        [Input("listenerId", required: true)]
        public string ListenerId { get; set; } = null!;

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        [Input("ruleId")]
        public string? RuleId { get; set; }

        [Input("scheduler")]
        public string? Scheduler { get; set; }

        [Input("url")]
        public string? Url { get; set; }

        public GetListenerRulesArgs()
        {
        }
        public static new GetListenerRulesArgs Empty => new GetListenerRulesArgs();
    }

    public sealed class GetListenerRulesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("clbId", required: true)]
        public Input<string> ClbId { get; set; } = null!;

        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("listenerId", required: true)]
        public Input<string> ListenerId { get; set; } = null!;

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        [Input("ruleId")]
        public Input<string>? RuleId { get; set; }

        [Input("scheduler")]
        public Input<string>? Scheduler { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        public GetListenerRulesInvokeArgs()
        {
        }
        public static new GetListenerRulesInvokeArgs Empty => new GetListenerRulesInvokeArgs();
    }


    [OutputType]
    public sealed class GetListenerRulesResult
    {
        public readonly string ClbId;
        public readonly string? Domain;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string ListenerId;
        public readonly string? ResultOutputFile;
        public readonly string? RuleId;
        public readonly ImmutableArray<Outputs.GetListenerRulesRuleListResult> RuleLists;
        public readonly string? Scheduler;
        public readonly string? Url;

        [OutputConstructor]
        private GetListenerRulesResult(
            string clbId,

            string? domain,

            string id,

            string listenerId,

            string? resultOutputFile,

            string? ruleId,

            ImmutableArray<Outputs.GetListenerRulesRuleListResult> ruleLists,

            string? scheduler,

            string? url)
        {
            ClbId = clbId;
            Domain = domain;
            Id = id;
            ListenerId = listenerId;
            ResultOutputFile = resultOutputFile;
            RuleId = ruleId;
            RuleLists = ruleLists;
            Scheduler = scheduler;
            Url = url;
        }
    }
}
