// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getBucketObject(args: GetBucketObjectArgs, opts?: pulumi.InvokeOptions): Promise<GetBucketObjectResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Cos/getBucketObject:getBucketObject", {
        "bucket": args.bucket,
        "key": args.key,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getBucketObject.
 */
export interface GetBucketObjectArgs {
    bucket: string;
    key: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getBucketObject.
 */
export interface GetBucketObjectResult {
    readonly bucket: string;
    readonly cacheControl: string;
    readonly contentDisposition: string;
    readonly contentEncoding: string;
    readonly contentType: string;
    readonly etag: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly key: string;
    readonly lastModified: string;
    readonly resultOutputFile?: string;
    readonly storageClass: string;
}
export function getBucketObjectOutput(args: GetBucketObjectOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetBucketObjectResult> {
    return pulumi.output(args).apply((a: any) => getBucketObject(a, opts))
}

/**
 * A collection of arguments for invoking getBucketObject.
 */
export interface GetBucketObjectOutputArgs {
    bucket: pulumi.Input<string>;
    key: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
