// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scf

import (
	"context"
	"reflect"

	"github.com/mergtil/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetFunctionVersions(ctx *pulumi.Context, args *GetFunctionVersionsArgs, opts ...pulumi.InvokeOption) (*GetFunctionVersionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetFunctionVersionsResult
	err := ctx.Invoke("tencentcloud:Scf/getFunctionVersions:getFunctionVersions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFunctionVersions.
type GetFunctionVersionsArgs struct {
	FunctionName     string  `pulumi:"functionName"`
	Namespace        *string `pulumi:"namespace"`
	Order            *string `pulumi:"order"`
	OrderBy          *string `pulumi:"orderBy"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getFunctionVersions.
type GetFunctionVersionsResult struct {
	FunctionName string `pulumi:"functionName"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                       `pulumi:"id"`
	Namespace        *string                      `pulumi:"namespace"`
	Order            *string                      `pulumi:"order"`
	OrderBy          *string                      `pulumi:"orderBy"`
	ResultOutputFile *string                      `pulumi:"resultOutputFile"`
	Versions         []GetFunctionVersionsVersion `pulumi:"versions"`
}

func GetFunctionVersionsOutput(ctx *pulumi.Context, args GetFunctionVersionsOutputArgs, opts ...pulumi.InvokeOption) GetFunctionVersionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetFunctionVersionsResult, error) {
			args := v.(GetFunctionVersionsArgs)
			r, err := GetFunctionVersions(ctx, &args, opts...)
			var s GetFunctionVersionsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetFunctionVersionsResultOutput)
}

// A collection of arguments for invoking getFunctionVersions.
type GetFunctionVersionsOutputArgs struct {
	FunctionName     pulumi.StringInput    `pulumi:"functionName"`
	Namespace        pulumi.StringPtrInput `pulumi:"namespace"`
	Order            pulumi.StringPtrInput `pulumi:"order"`
	OrderBy          pulumi.StringPtrInput `pulumi:"orderBy"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetFunctionVersionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFunctionVersionsArgs)(nil)).Elem()
}

// A collection of values returned by getFunctionVersions.
type GetFunctionVersionsResultOutput struct{ *pulumi.OutputState }

func (GetFunctionVersionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFunctionVersionsResult)(nil)).Elem()
}

func (o GetFunctionVersionsResultOutput) ToGetFunctionVersionsResultOutput() GetFunctionVersionsResultOutput {
	return o
}

func (o GetFunctionVersionsResultOutput) ToGetFunctionVersionsResultOutputWithContext(ctx context.Context) GetFunctionVersionsResultOutput {
	return o
}

func (o GetFunctionVersionsResultOutput) FunctionName() pulumi.StringOutput {
	return o.ApplyT(func(v GetFunctionVersionsResult) string { return v.FunctionName }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetFunctionVersionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFunctionVersionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetFunctionVersionsResultOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFunctionVersionsResult) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

func (o GetFunctionVersionsResultOutput) Order() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFunctionVersionsResult) *string { return v.Order }).(pulumi.StringPtrOutput)
}

func (o GetFunctionVersionsResultOutput) OrderBy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFunctionVersionsResult) *string { return v.OrderBy }).(pulumi.StringPtrOutput)
}

func (o GetFunctionVersionsResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFunctionVersionsResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetFunctionVersionsResultOutput) Versions() GetFunctionVersionsVersionArrayOutput {
	return o.ApplyT(func(v GetFunctionVersionsResult) []GetFunctionVersionsVersion { return v.Versions }).(GetFunctionVersionsVersionArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFunctionVersionsResultOutput{})
}
